function [rLeftShank,vLeftShank,omegaLeftShank,ILeftShank,RLeftShank] = autoGen_LeftShank(rOx,rOy,rOz,alpha,beta,gamma,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,rOxdot,rOydot,rOzdot,alphadot,betadot,gammadot,q1dot,q2dot,q3dot,q4dot,q5dot,q6dot,q7dot,q8dot,q9dot,q10dot,q11dot,q12dot,q13dot,q14dot,q15dot,q16dot)
%AUTOGEN_LEFTSHANK
%    [RLEFTSHANK,VLEFTSHANK,OMEGALEFTSHANK,ILEFTSHANK,RLEFTSHANK] = AUTOGEN_LEFTSHANK(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Oct-2018 20:28:49

t2 = sin(alpha);
t3 = cos(alpha);
t4 = beta-q12;
t5 = sin(gamma);
t6 = sin(t4);
t7 = gamma-q13;
t8 = -gamma+q13+q14;
t9 = cos(gamma);
t10 = sin(beta);
t11 = cos(t4);
t12 = sin(t7);
t13 = sin(t8);
t14 = cos(beta);
t15 = cos(t7);
t16 = cos(t8);
t17 = t3.*t12.*5.55e-2;
t18 = t3.*t5.*1.2766659e-1;
t19 = t2.*t5.*t10.*2.330279e-2;
t20 = t2.*t16.*3.29934e-2;
t21 = t3.*t6.*t13.*3.29934e-2;
t22 = t2.*t15.*5.55e-2;
t23 = t3.*t11.*t15.*5.55e-2;
t24 = t3.*t11.*t16.*3.29934e-2;
t25 = t3.*t9.*t11.*(7.0./2.0e2);
t26 = t3.*t5.*t11.*3.225e-2;
t27 = t3.*t16.*3.29934e-2;
t28 = t3.*t15.*5.55e-2;
t29 = t2.*t6.*t12.*5.55e-2;
t30 = t2.*t5.*t11.*3.225e-2;
t31 = t2.*t11.*t15.*5.55e-2;
t32 = t2.*t11.*t16.*3.29934e-2;
t33 = t2.*t9.*t11.*(7.0./2.0e2);
t34 = t2.*t13.*3.29934e-2;
t35 = t2.*t9.*8.94721e-3;
t36 = t3.*t5.*t10.*2.330279e-2;
rLeftShank = [rOx+t34+t35+t36-t2.*t5.*1.2766659e-1-t2.*t12.*5.55e-2-t3.*t11.*1.088657e-2-t3.*t14.*3.172834e-2-t3.*t5.*t6.*3.225e-2-t3.*t6.*t9.*(7.0./2.0e2)-t3.*t9.*t10.*9.266658999999999e-2-t3.*t6.*t15.*5.55e-2-t3.*t6.*t16.*3.29934e-2;rOy+t17+t18+t19-t3.*t9.*8.94721e-3-t2.*t11.*1.088657e-2-t2.*t14.*3.172834e-2-t3.*t13.*3.29934e-2-t2.*t5.*t6.*3.225e-2-t2.*t6.*t9.*(7.0./2.0e2)-t2.*t9.*t10.*9.266658999999999e-2-t2.*t6.*t15.*5.55e-2-t2.*t6.*t16.*3.29934e-2;rOz+t6.*1.088657e-2+t10.*3.172834e-2-t5.*t11.*3.225e-2+t5.*t14.*2.330279e-2-t9.*t11.*(7.0./2.0e2)-t9.*t14.*9.266658999999999e-2-t11.*t15.*5.55e-2-t11.*t16.*3.29934e-2];
if nargout > 1
    t37 = t11.*t12.*5.55e-2;
    t38 = t11.*1.088657e-2;
    t39 = t6.*t9.*(7.0./2.0e2);
    t40 = t5.*t6.*3.225e-2;
    t41 = t6.*t15.*5.55e-2;
    t42 = t6.*t16.*3.29934e-2;
    vLeftShank = [rOxdot+q14dot.*(t20+t21)-betadot.*(t23+t24+t25+t26-t3.*t6.*1.088657e-2-t3.*t10.*3.172834e-2-t3.*t5.*t14.*2.330279e-2+t3.*t9.*t14.*9.266658999999999e-2)+q13dot.*(t20+t21+t22-t3.*t6.*t12.*5.55e-2)+q12dot.*(t23+t24+t25+t26-t3.*t6.*1.088657e-2)+alphadot.*(-t17-t18-t19+t3.*t9.*8.94721e-3+t2.*t11.*1.088657e-2+t2.*t14.*3.172834e-2+t3.*t13.*3.29934e-2+t2.*t5.*t6.*3.225e-2+t2.*t6.*t9.*(7.0./2.0e2)+t2.*t9.*t10.*9.266658999999999e-2+t2.*t6.*t15.*5.55e-2+t2.*t6.*t16.*3.29934e-2)-gammadot.*(t20+t21+t22+t2.*t5.*8.94721e-3+t2.*t9.*1.2766659e-1-t3.*t5.*t6.*(7.0./2.0e2)-t3.*t5.*t10.*9.266658999999999e-2+t3.*t6.*t9.*3.225e-2-t3.*t6.*t12.*5.55e-2-t3.*t9.*t10.*2.330279e-2);rOydot-q13dot.*(t27+t28+t29-t2.*t6.*t13.*3.29934e-2)-q14dot.*(t27-t2.*t6.*t13.*3.29934e-2)-betadot.*(t30+t31+t32+t33-t2.*t6.*1.088657e-2-t2.*t10.*3.172834e-2-t2.*t5.*t14.*2.330279e-2+t2.*t9.*t14.*9.266658999999999e-2)+q12dot.*(t30+t31+t32+t33-t2.*t6.*1.088657e-2)+gammadot.*(t27+t28+t29+t3.*t5.*8.94721e-3+t3.*t9.*1.2766659e-1+t2.*t5.*t6.*(7.0./2.0e2)+t2.*t5.*t10.*9.266658999999999e-2-t2.*t6.*t9.*3.225e-2-t2.*t6.*t13.*3.29934e-2+t2.*t9.*t10.*2.330279e-2)-alphadot.*(-t34-t35-t36+t2.*t5.*1.2766659e-1+t2.*t12.*5.55e-2+t3.*t11.*1.088657e-2+t3.*t14.*3.172834e-2+t3.*t5.*t6.*3.225e-2+t3.*t6.*t9.*(7.0./2.0e2)+t3.*t9.*t10.*9.266658999999999e-2+t3.*t6.*t15.*5.55e-2+t3.*t6.*t16.*3.29934e-2);rOzdot-q12dot.*(t38+t39+t40+t41+t42)+gammadot.*(t37+t5.*t11.*(7.0./2.0e2)+t5.*t14.*9.266658999999999e-2-t9.*t11.*3.225e-2+t9.*t14.*2.330279e-2-t11.*t13.*3.29934e-2)-q13dot.*(t37-t11.*t13.*3.29934e-2)+betadot.*(t14.*3.172834e-2+t38+t39+t40+t41+t42-t5.*t10.*2.330279e-2+t9.*t10.*9.266658999999999e-2)+q14dot.*t11.*t13.*3.29934e-2];
end
if nargout > 2
    t43 = betadot-q12dot;
    omegaLeftShank = [gammadot-q13dot-q14dot-alphadot.*t6;t16.*t43-alphadot.*t11.*t13;t13.*t43+alphadot.*t11.*t16];
end
if nargout > 3
    ILeftShank = reshape([1.0e-4,0.0,0.0,0.0,1.0e-4,0.0,0.0,0.0,3.7987e-5],[3,3]);
end
if nargout > 4
    RLeftShank = reshape([t3.*t11,t2.*t11,-t6,-t2.*t16-t3.*t6.*t13,t3.*t16-t2.*t6.*t13,-t11.*t13,-t2.*t13+t3.*t6.*t16,t3.*t13+t2.*t6.*t16,t11.*t16],[3,3]);
end
