function [rRightShoulder,vRightShoulder,omegaRightShoulder,IRightShoulder,RRightShoulder] = autoGen_RightShoulder(rOx,rOy,rOz,alpha,beta,gamma,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,rOxdot,rOydot,rOzdot,alphadot,betadot,gammadot,q1dot,q2dot,q3dot,q4dot,q5dot,q6dot,q7dot,q8dot,q9dot,q10dot,q11dot,q12dot,q13dot,q14dot,q15dot,q16dot)
%AUTOGEN_RIGHTSHOULDER
%    [RRIGHTSHOULDER,VRIGHTSHOULDER,OMEGARIGHTSHOULDER,IRIGHTSHOULDER,RRIGHTSHOULDER] = AUTOGEN_RIGHTSHOULDER(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Oct-2018 20:28:43

t2 = cos(alpha);
t3 = sin(alpha);
t4 = cos(gamma);
t5 = sin(beta);
t6 = sin(gamma);
t10 = pi.*(1.0./1.8e1);
t7 = beta-t10;
t8 = cos(t7);
t9 = cos(beta);
t11 = t3.*t8.*4.23081e-3;
t12 = t3.*t9.*6.272722e-2;
t13 = t3.*t4.*t5.*3.18887e-2;
t14 = sin(t7);
t15 = t3.*t6.*3.18887e-2;
t16 = t2.*t9.*6.272722e-2;
t17 = t2.*t8.*4.23081e-3;
t18 = t3.*t4.*1.64721e-3;
t19 = t2.*t4.*t5.*3.18887e-2;
rRightShoulder = [rOx+t15+t16+t17+t18+t19-t2.*t5.*t6.*1.64721e-3;rOy+t11+t12+t13-t2.*t4.*1.64721e-3-t2.*t6.*3.18887e-2-t3.*t5.*t6.*1.64721e-3;rOz-t5.*6.272722e-2-t14.*4.23081e-3+t4.*t9.*3.18887e-2-t6.*t9.*1.64721e-3];
if nargout > 1
    vRightShoulder = [rOxdot-alphadot.*(t11+t12+t13-t2.*t4.*1.64721e-3-t2.*t6.*3.18887e-2-t3.*t5.*t6.*1.64721e-3)-betadot.*(t2.*t5.*6.272722e-2+t2.*t14.*4.23081e-3-t2.*t4.*t9.*3.18887e-2+t2.*t6.*t9.*1.64721e-3)-gammadot.*(t3.*t4.*(-3.18887e-2)+t3.*t6.*1.64721e-3+t2.*t4.*t5.*1.64721e-3+t2.*t5.*t6.*3.18887e-2);rOydot+alphadot.*(t15+t16+t17+t18+t19-t2.*t5.*t6.*1.64721e-3)-betadot.*(t3.*t5.*6.272722e-2+t3.*t14.*4.23081e-3-t3.*t4.*t9.*3.18887e-2+t3.*t6.*t9.*1.64721e-3)-gammadot.*(t2.*t4.*3.18887e-2-t2.*t6.*1.64721e-3+t3.*t4.*t5.*1.64721e-3+t3.*t5.*t6.*3.18887e-2);rOzdot-gammadot.*(t4.*t9.*1.64721e-3+t6.*t9.*3.18887e-2)-betadot.*(t8.*4.23081e-3+t9.*6.272722e-2+t4.*t5.*3.18887e-2-t5.*t6.*1.64721e-3)];
end
if nargout > 2
    t20 = gamma+q9;
    t21 = sin(t20);
    t22 = cos(t20);
    omegaRightShoulder = [gammadot+q9dot-alphadot.*t14;betadot.*t22+alphadot.*t8.*t21;-betadot.*t21+alphadot.*t8.*t22];
end
if nargout > 3
    IRightShoulder = reshape([3.6e-6,0.0,0.0,0.0,7.698e-7,0.0,0.0,0.0,3.6e-6],[3,3]);
end
if nargout > 4
    RRightShoulder = reshape([t2.*t8,t3.*t8,-t14,-t3.*t22+t2.*t14.*t21,t2.*t22+t3.*t14.*t21,t8.*t21,t3.*t21+t2.*t14.*t22,-t2.*t21+t3.*t14.*t22,t8.*t22],[3,3]);
end
