function [rLeftShoulder,vLeftShoulder,omegaLeftShoulder,ILeftShoulder,RLeftShoulder] = autoGen_LeftShoulder(rOx,rOy,rOz,alpha,beta,gamma,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,rOxdot,rOydot,rOzdot,alphadot,betadot,gammadot,q1dot,q2dot,q3dot,q4dot,q5dot,q6dot,q7dot,q8dot,q9dot,q10dot,q11dot,q12dot,q13dot,q14dot,q15dot,q16dot)
%AUTOGEN_LEFTSHOULDER
%    [RLEFTSHOULDER,VLEFTSHOULDER,OMEGALEFTSHOULDER,ILEFTSHOULDER,RLEFTSHOULDER] = AUTOGEN_LEFTSHOULDER(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Oct-2018 20:28:40

t2 = cos(alpha);
t3 = sin(alpha);
t4 = cos(gamma);
t5 = sin(beta);
t6 = sin(gamma);
t7 = pi.*(1.0./1.8e1);
t8 = beta+t7;
t9 = cos(t8);
t10 = cos(beta);
t11 = t3.*t4.*t5.*3.18887e-2;
t12 = sin(t8);
t13 = t3.*t6.*3.18887e-2;
t14 = t3.*t4.*1.64721e-3;
t15 = t2.*t4.*t5.*3.18887e-2;
rLeftShoulder = [rOx+t13+t14+t15-t2.*t9.*4.23081e-3-t2.*t10.*6.272722e-2-t2.*t5.*t6.*1.64721e-3;rOy+t11-t2.*t4.*1.64721e-3-t2.*t6.*3.18887e-2-t3.*t9.*4.23081e-3-t3.*t10.*6.272722e-2-t3.*t5.*t6.*1.64721e-3;rOz+t5.*6.272722e-2+t12.*4.23081e-3+t4.*t10.*3.18887e-2-t6.*t10.*1.64721e-3];
if nargout > 1
    vLeftShoulder = [rOxdot+alphadot.*(-t11+t2.*t4.*1.64721e-3+t2.*t6.*3.18887e-2+t3.*t9.*4.23081e-3+t3.*t10.*6.272722e-2+t3.*t5.*t6.*1.64721e-3)+betadot.*(t2.*t5.*6.272722e-2+t2.*t12.*4.23081e-3+t2.*t4.*t10.*3.18887e-2-t2.*t6.*t10.*1.64721e-3)-gammadot.*(t3.*t4.*(-3.18887e-2)+t3.*t6.*1.64721e-3+t2.*t4.*t5.*1.64721e-3+t2.*t5.*t6.*3.18887e-2);rOydot+betadot.*(t3.*t5.*6.272722e-2+t3.*t12.*4.23081e-3+t3.*t4.*t10.*3.18887e-2-t3.*t6.*t10.*1.64721e-3)+alphadot.*(t13+t14+t15-t2.*t9.*4.23081e-3-t2.*t10.*6.272722e-2-t2.*t5.*t6.*1.64721e-3)-gammadot.*(t2.*t4.*3.18887e-2-t2.*t6.*1.64721e-3+t3.*t4.*t5.*1.64721e-3+t3.*t5.*t6.*3.18887e-2);rOzdot-gammadot.*(t4.*t10.*1.64721e-3+t6.*t10.*3.18887e-2)+betadot.*(t9.*4.23081e-3+t10.*6.272722e-2-t4.*t5.*3.18887e-2+t5.*t6.*1.64721e-3)];
end
if nargout > 2
    t16 = gamma-q1;
    t17 = sin(t16);
    t18 = cos(t16);
    omegaLeftShoulder = [gammadot-q1dot-alphadot.*t12;betadot.*t18+alphadot.*t9.*t17;-betadot.*t17+alphadot.*t9.*t18];
end
if nargout > 3
    ILeftShoulder = reshape([3.6e-6,0.0,0.0,0.0,7.698e-7,0.0,0.0,0.0,3.6e-6],[3,3]);
end
if nargout > 4
    RLeftShoulder = reshape([t2.*t9,t3.*t9,-t12,-t3.*t18+t2.*t12.*t17,t2.*t18+t3.*t12.*t17,t9.*t17,t3.*t17+t2.*t12.*t18,-t2.*t17+t3.*t12.*t18,t9.*t18],[3,3]);
end
