function [rRightShoulder,vRightShoulder,omegaRightShoulder,IRightShoulder,RRightShoulder] = autoGen_RightShoulder(State)
%AUTOGEN_RIGHTSHOULDER
%    [RRIGHTSHOULDER,VRIGHTSHOULDER,OMEGARIGHTSHOULDER,IRIGHTSHOULDER,RRIGHTSHOULDER] = AUTOGEN_RIGHTSHOULDER(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Oct-2018 20:28:43

rOx = State(1);                 
rOy = State(2);
rOz = State(3);
alpha = State(4);
beta = State(5);
gamma = State(6);
q1 = State(7);
q2 = State(7+1);
q3 = State(7+2);
q4 = State(7+3);
q5 = State(7+4);
q6 = State(7+5);
q7 = State(7+6);
q8 = State(7+7);
q9 = State(7+8);
q10 = State(7+9);
q11 = State(7+10);
q12 = State(7+11);
q13 = State(7+12);
q14 = State(7+13);
q15 = State(7+14);
q16 = State(7+15);

rOxdot = State(1 + 22);                 
rOydot = State(2+ 22);
rOzdot = State(3+ 22);
alphadot = State(4+ 22);
betadot = State(5+ 22);
gammadot = State(6+ 22);
q1dot = State(7+ 22);
q2dot = State(7+1+ 22);
q3dot = State(7+2+ 22);
q4dot = State(7+3+ 22);
q5dot = State(7+4+ 22);
q6dot = State(7+5+ 22);
q7dot = State(7+6+ 22);
q8dot = State(7+7+ 22);
q9dot = State(7+8+ 22);
q10dot = State(7+9+ 22);
q11dot = State(7+10+ 22);
q12dot = State(7+11+ 22);
q13dot = State(7+12+ 22);
q14dot = State(7+13+ 22);
q15dot = State(7+14+ 22);
q16dot = State(7+15+ 22);

t2 = cos(alpha);
t3 = sin(alpha);
t4 = cos(gamma);
t5 = sin(beta);
t6 = sin(gamma);
t10 = pi.*(1.0./1.8e1);
t7 = beta-t10;
t8 = cos(t7);
t9 = cos(beta);
t11 = t3.*t8.*4.23081e-3;
t12 = t3.*t9.*6.272722e-2;
t13 = t3.*t4.*t5.*3.18887e-2;
t14 = sin(t7);
t15 = t3.*t6.*3.18887e-2;
t16 = t2.*t9.*6.272722e-2;
t17 = t2.*t8.*4.23081e-3;
t18 = t3.*t4.*1.64721e-3;
t19 = t2.*t4.*t5.*3.18887e-2;
rRightShoulder = [rOx+t15+t16+t17+t18+t19-t2.*t5.*t6.*1.64721e-3;rOy+t11+t12+t13-t2.*t4.*1.64721e-3-t2.*t6.*3.18887e-2-t3.*t5.*t6.*1.64721e-3;rOz-t5.*6.272722e-2-t14.*4.23081e-3+t4.*t9.*3.18887e-2-t6.*t9.*1.64721e-3];
if nargout > 1
    vRightShoulder = [rOxdot-alphadot.*(t11+t12+t13-t2.*t4.*1.64721e-3-t2.*t6.*3.18887e-2-t3.*t5.*t6.*1.64721e-3)-betadot.*(t2.*t5.*6.272722e-2+t2.*t14.*4.23081e-3-t2.*t4.*t9.*3.18887e-2+t2.*t6.*t9.*1.64721e-3)-gammadot.*(t3.*t4.*(-3.18887e-2)+t3.*t6.*1.64721e-3+t2.*t4.*t5.*1.64721e-3+t2.*t5.*t6.*3.18887e-2);rOydot+alphadot.*(t15+t16+t17+t18+t19-t2.*t5.*t6.*1.64721e-3)-betadot.*(t3.*t5.*6.272722e-2+t3.*t14.*4.23081e-3-t3.*t4.*t9.*3.18887e-2+t3.*t6.*t9.*1.64721e-3)-gammadot.*(t2.*t4.*3.18887e-2-t2.*t6.*1.64721e-3+t3.*t4.*t5.*1.64721e-3+t3.*t5.*t6.*3.18887e-2);rOzdot-gammadot.*(t4.*t9.*1.64721e-3+t6.*t9.*3.18887e-2)-betadot.*(t8.*4.23081e-3+t9.*6.272722e-2+t4.*t5.*3.18887e-2-t5.*t6.*1.64721e-3)];
end
if nargout > 2
    t20 = gamma+q9;
    t21 = sin(t20);
    t22 = cos(t20);
    omegaRightShoulder = [gammadot+q9dot-alphadot.*t14;betadot.*t22+alphadot.*t8.*t21;-betadot.*t21+alphadot.*t8.*t22];
end
if nargout > 3
    IRightShoulder = reshape([3.6e-6,0.0,0.0,0.0,7.698e-7,0.0,0.0,0.0,3.6e-6],[3,3]);
end
if nargout > 4
    RRightShoulder = reshape([t2.*t8,t3.*t8,-t14,-t3.*t22+t2.*t14.*t21,t2.*t22+t3.*t14.*t21,t8.*t21,t3.*t21+t2.*t14.*t22,-t2.*t21+t3.*t14.*t22,t8.*t22],[3,3]);
end
