function [rRightArm,vRightArm,omegaRightArm,IRightArm,RRightArm] = autoGen_RightArm(rOx,rOy,rOz,alpha,beta,gamma,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,rOxdot,rOydot,rOzdot,alphadot,betadot,gammadot,q1dot,q2dot,q3dot,q4dot,q5dot,q6dot,q7dot,q8dot,q9dot,q10dot,q11dot,q12dot,q13dot,q14dot,q15dot,q16dot)
%AUTOGEN_RIGHTARM
%    [RRIGHTARM,VRIGHTARM,OMEGARIGHTARM,IRIGHTARM,RRIGHTARM] = AUTOGEN_RIGHTARM(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Oct-2018 20:28:44

t2 = sin(alpha);
t3 = cos(alpha);
t7 = pi.*(1.0./1.8e1);
t4 = beta+q10-t7;
t5 = gamma+q9;
t6 = sin(t5);
t8 = cos(gamma);
t9 = sin(beta);
t10 = sin(gamma);
t11 = beta-t7;
t12 = cos(t4);
t13 = cos(t5);
t14 = cos(beta);
t15 = sin(t4);
t16 = sin(t11);
t17 = cos(t11);
t18 = t2.*t17.*1.950677e-2;
t19 = t2.*t12.*3.595415e-2;
t20 = t2.*t14.*6.272722e-2;
t21 = t2.*t6.*t16.*2.575e-2;
t22 = t2.*t8.*t9.*3.18887e-2;
t23 = t3.*t15.*3.595415e-2;
t24 = t3.*t6.*t12.*2.621678e-2;
t25 = t2.*t6.*4.667799999999986e-4;
t26 = t3.*t13.*t15.*2.621678e-2;
t27 = t2.*t15.*3.595415e-2;
t28 = t2.*t6.*t12.*2.621678e-2;
t29 = t3.*t6.*4.667799999999986e-4;
t30 = t2.*t13.*t16.*2.575e-2;
t31 = t2.*t10.*3.18887e-2;
t32 = t3.*t12.*3.595415e-2;
t33 = t2.*t13.*4.667799999999986e-4;
t34 = t3.*t14.*6.272722e-2;
t35 = t2.*t8.*1.64721e-3;
t36 = t3.*t6.*t16.*2.575e-2;
t37 = t3.*t8.*t9.*3.18887e-2;
rRightArm = [rOx+t31+t32+t33+t34+t35+t36+t37+t3.*cos(beta-pi.*(1.0./1.8e1)).*1.950677e-2-t3.*t9.*t10.*1.64721e-3-t3.*t6.*t15.*2.621678e-2;rOy+t18+t19+t20+t21+t22-t3.*t8.*1.64721e-3-t3.*t10.*3.18887e-2-t3.*t13.*4.667799999999986e-4-t2.*t9.*t10.*1.64721e-3-t2.*t6.*t15.*2.621678e-2;rOz-t9.*6.272722e-2-t15.*3.595415e-2-t16.*1.950677e-2-t6.*t12.*2.621678e-2+t8.*t14.*3.18887e-2+t6.*t17.*2.575e-2-t10.*t14.*1.64721e-3];
if nargout > 1
    t38 = t12.*t13.*2.621678e-2;
    t39 = t12.*3.595415e-2;
    vRightArm = [rOxdot-q10dot.*(t23+t24)-gammadot.*(t25+t26-t2.*t8.*3.18887e-2+t2.*t10.*1.64721e-3+t3.*t8.*t9.*1.64721e-3+t3.*t9.*t10.*3.18887e-2-t3.*t13.*t16.*2.575e-2)-betadot.*(t23+t24+t3.*t9.*6.272722e-2+t3.*t16.*1.950677e-2-t3.*t8.*t14.*3.18887e-2-t3.*t6.*t17.*2.575e-2+t3.*t10.*t14.*1.64721e-3)-q9dot.*(t25+t26-t3.*t13.*t16.*2.575e-2)-alphadot.*(t18+t19+t20+t21+t22-t3.*t8.*1.64721e-3-t3.*t10.*3.18887e-2-t3.*t13.*4.667799999999986e-4-t2.*t9.*t10.*1.64721e-3-t2.*t6.*t15.*2.621678e-2);rOydot+alphadot.*(t31+t32+t33+t34+t35+t36+t37+t3.*t17.*1.950677e-2-t3.*t9.*t10.*1.64721e-3-t3.*t6.*t15.*2.621678e-2)-q10dot.*(t27+t28)+q9dot.*(t29+t30-t2.*t13.*t15.*2.621678e-2)-gammadot.*(-t29-t30+t3.*t8.*3.18887e-2-t3.*t10.*1.64721e-3+t2.*t8.*t9.*1.64721e-3+t2.*t9.*t10.*3.18887e-2+t2.*t13.*t15.*2.621678e-2)-betadot.*(t27+t28+t2.*t9.*6.272722e-2+t2.*t16.*1.950677e-2-t2.*t8.*t14.*3.18887e-2-t2.*t6.*t17.*2.575e-2+t2.*t10.*t14.*1.64721e-3);rOzdot-q10dot.*(t39-t6.*t15.*2.621678e-2)-betadot.*(t14.*6.272722e-2+t17.*1.950677e-2+t39+t8.*t9.*3.18887e-2-t9.*t10.*1.64721e-3-t6.*t15.*2.621678e-2+t6.*t16.*2.575e-2)-gammadot.*(t38+t8.*t14.*1.64721e-3+t10.*t14.*3.18887e-2-t13.*t17.*2.575e-2)-q9dot.*(t38-t13.*t17.*2.575e-2)];
end
if nargout > 2
    t40 = betadot+q10dot;
    omegaRightArm = [gammadot+q9dot-alphadot.*t15;t13.*t40+alphadot.*t6.*t12;-t6.*t40+alphadot.*t12.*t13];
end
if nargout > 3
    IRightArm = reshape([3.515445e-5,0.0,0.0,0.0,1.25e-4,0.0,0.0,0.0,1.25e-4],[3,3]);
end
if nargout > 4
    RRightArm = reshape([t3.*t12,t2.*t12,-t15,-t2.*t13+t3.*t6.*t15,t3.*t13+t2.*t6.*t15,t6.*t12,t2.*t6+t3.*t13.*t15,-t3.*t6+t2.*t13.*t15,t12.*t13],[3,3]);
end
