function [rBody,vBody,omegaBody,IBody,RBody] = autoGen_Body(State)
%AUTOGEN_BODY
%    [RBODY,VBODY,OMEGABODY,IBODY,RBODY] = AUTOGEN_BODY(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Oct-2018 20:28:38

rOx = State(1);                 
rOy = State(2);
rOz = State(3);
alpha = State(4);
beta = State(5);
gamma = State(6);
q1 = State(7);
q2 = State(7+1);
q3 = State(7+2);
q4 = State(7+3);
q5 = State(7+4);
q6 = State(7+5);
q7 = State(7+6);
q8 = State(7+7);
q9 = State(7+8);
q10 = State(7+9);
q11 = State(7+10);
q12 = State(7+11);
q13 = State(7+12);
q14 = State(7+13);
q15 = State(7+14);
q16 = State(7+15);

rOxdot = State(1 + 22);                 
rOydot = State(2+ 22);
rOzdot = State(3+ 22);
alphadot = State(4+ 22);
betadot = State(5+ 22);
gammadot = State(6+ 22);
q1dot = State(7+ 22);
q2dot = State(7+1+ 22);
q3dot = State(7+2+ 22);
q4dot = State(7+3+ 22);
q5dot = State(7+4+ 22);
q6dot = State(7+5+ 22);
q7dot = State(7+6+ 22);
q8dot = State(7+7+ 22);
q9dot = State(7+8+ 22);
q10dot = State(7+9+ 22);
q11dot = State(7+10+ 22);
q12dot = State(7+11+ 22);
q13dot = State(7+12+ 22);
q14dot = State(7+13+ 22);
q15dot = State(7+14+ 22);
q16dot = State(7+15+ 22);

rBody = [rOx;rOy;rOz];
if nargout > 1
    vBody = [rOxdot;rOydot;rOzdot];
end
if nargout > 2
    t2 = sin(gamma);
    t3 = cos(beta);
    t4 = cos(gamma);
    t5 = cos(alpha);
    t6 = sin(beta);
    omegaBody = [gammadot-alphadot.*t6;betadot.*t4+alphadot.*t2.*t3;-betadot.*t2+alphadot.*t3.*t4];
end
if nargout > 3
    IBody = reshape([1.0./4.0e2,0.0,0.0,0.0,1.0./4.0e2,0.0,0.0,0.0,1.0./1.0e3],[3,3]);
end
if nargout > 4
    t7 = sin(alpha);
    RBody = reshape([t3.*t5,t3.*t7,-t6,-t4.*t7+t2.*t5.*t6,t4.*t5+t2.*t6.*t7,t2.*t3,t2.*t7+t4.*t5.*t6,-t2.*t5+t4.*t6.*t7,t3.*t4],[3,3]);
end
