function [rRightHip,vRightHip,omegaRightHip,IRightHip,RRightHip] = autoGen_RightHip(rOx,rOy,rOz,alpha,beta,gamma,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,rOxdot,rOydot,rOzdot,alphadot,betadot,gammadot,q1dot,q2dot,q3dot,q4dot,q5dot,q6dot,q7dot,q8dot,q9dot,q10dot,q11dot,q12dot,q13dot,q14dot,q15dot,q16dot)
%AUTOGEN_RIGHTHIP
%    [RRIGHTHIP,VRIGHTHIP,OMEGARIGHTHIP,IRIGHTHIP,RRIGHTHIP] = AUTOGEN_RIGHTHIP(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Oct-2018 20:28:55

t2 = cos(alpha);
t3 = sin(alpha);
t4 = beta-q4;
t5 = sin(gamma);
t6 = cos(gamma);
t7 = sin(beta);
t8 = sin(t4);
t9 = cos(t4);
t10 = cos(beta);
t11 = t2.*t8.*1.065566e-2;
t12 = t2.*t6.*t9.*2.68635e-3;
t13 = t2.*t5.*t9.*1.458538e-2;
t14 = t3.*t9.*1.065566e-2;
t15 = t2.*t6.*8.71741e-3;
t16 = t3.*t10.*3.172834e-2;
t17 = t2.*t5.*9.535293999999999e-2;
t18 = t3.*t5.*t7.*2.330279e-2;
t19 = t3.*t8.*1.065566e-2;
t20 = t3.*t5.*t9.*1.458538e-2;
t21 = t3.*t6.*t9.*2.68635e-3;
t22 = t2.*t9.*1.065566e-2;
t23 = t2.*t10.*3.172834e-2;
t24 = t2.*t5.*t7.*2.330279e-2;
rRightHip = [rOx+t22+t23+t24-t3.*t5.*9.535293999999999e-2-t3.*t6.*8.71741e-3-t2.*t5.*t8.*1.458538e-2-t2.*t6.*t7.*9.266658999999999e-2-t2.*t6.*t8.*2.68635e-3;rOy+t14+t15+t16+t17+t18-t3.*t5.*t8.*1.458538e-2-t3.*t6.*t7.*9.266658999999999e-2-t3.*t6.*t8.*2.68635e-3;rOz-t7.*3.172834e-2-t8.*1.065566e-2-t5.*t9.*1.458538e-2+t5.*t10.*2.330279e-2-t6.*t9.*2.68635e-3-t6.*t10.*9.266658999999999e-2];
if nargout > 1
    t25 = t9.*1.065566e-2;
    vRightHip = [rOxdot-alphadot.*(t14+t15+t16+t17+t18-t3.*t5.*t8.*1.458538e-2-t3.*t6.*t7.*9.266658999999999e-2-t3.*t6.*t8.*2.68635e-3)-betadot.*(t11+t12+t13+t2.*t7.*3.172834e-2-t2.*t5.*t10.*2.330279e-2+t2.*t6.*t10.*9.266658999999999e-2)+q4dot.*(t11+t12+t13)+gammadot.*(t3.*t5.*8.71741e-3-t3.*t6.*9.535293999999999e-2+t2.*t5.*t7.*9.266658999999999e-2+t2.*t5.*t8.*2.68635e-3+t2.*t6.*t7.*2.330279e-2-t2.*t6.*t8.*1.458538e-2);rOydot-betadot.*(t19+t20+t21+t3.*t7.*3.172834e-2-t3.*t5.*t10.*2.330279e-2+t3.*t6.*t10.*9.266658999999999e-2)+q4dot.*(t19+t20+t21)-alphadot.*(-t22-t23-t24+t3.*t5.*9.535293999999999e-2+t3.*t6.*8.71741e-3+t2.*t5.*t8.*1.458538e-2+t2.*t6.*t7.*9.266658999999999e-2+t2.*t6.*t8.*2.68635e-3)+gammadot.*(t2.*t5.*(-8.71741e-3)+t2.*t6.*9.535293999999999e-2+t3.*t5.*t7.*9.266658999999999e-2+t3.*t5.*t8.*2.68635e-3+t3.*t6.*t7.*2.330279e-2-t3.*t6.*t8.*1.458538e-2);rOzdot-q4dot.*(-t25+t5.*t8.*1.458538e-2+t6.*t8.*2.68635e-3)-betadot.*(t10.*3.172834e-2+t25+t5.*t7.*2.330279e-2-t5.*t8.*1.458538e-2-t6.*t7.*9.266658999999999e-2-t6.*t8.*2.68635e-3)+gammadot.*(t5.*t9.*2.68635e-3+t5.*t10.*9.266658999999999e-2-t6.*t9.*1.458538e-2+t6.*t10.*2.330279e-2)];
end
if nargout > 2
    t26 = betadot-q4dot;
    omegaRightHip = [gammadot-alphadot.*t8;t6.*t26+alphadot.*t5.*t9;-t5.*t26+alphadot.*t6.*t9];
end
if nargout > 3
    IRightHip = reshape([5.0e-5,0.0,0.0,0.0,5.0e-5,0.0,0.0,0.0,5.0e-5],[3,3]);
end
if nargout > 4
    RRightHip = reshape([t2.*t9,t3.*t9,-t8,-t3.*t6+t2.*t5.*t8,t2.*t6+t3.*t5.*t8,t5.*t9,t3.*t5+t2.*t6.*t8,-t2.*t5+t3.*t6.*t8,t6.*t9],[3,3]);
end
