function [rLeftHip,vLeftHip,omegaLeftHip,ILeftHip,RLeftHip] = autoGen_LeftHip(State)
%AUTOGEN_LEFTHIP
%    [RLEFTHIP,VLEFTHIP,OMEGALEFTHIP,ILEFTHIP,RLEFTHIP] = AUTOGEN_LEFTHIP(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Oct-2018 20:28:46

rOx = State(1);                 
rOy = State(2);
rOz = State(3);
alpha = State(4);
beta = State(5);
gamma = State(6);
q1 = State(7);
q2 = State(7+1);
q3 = State(7+2);
q4 = State(7+3);
q5 = State(7+4);
q6 = State(7+5);
q7 = State(7+6);
q8 = State(7+7);
q9 = State(7+8);
q10 = State(7+9);
q11 = State(7+10);
q12 = State(7+11);
q13 = State(7+12);
q14 = State(7+13);
q15 = State(7+14);
q16 = State(7+15);

rOxdot = State(1 + 22);                 
rOydot = State(2+ 22);
rOzdot = State(3+ 22);
alphadot = State(4+ 22);
betadot = State(5+ 22);
gammadot = State(6+ 22);
q1dot = State(7+ 22);
q2dot = State(7+1+ 22);
q3dot = State(7+2+ 22);
q4dot = State(7+3+ 22);
q5dot = State(7+4+ 22);
q6dot = State(7+5+ 22);
q7dot = State(7+6+ 22);
q8dot = State(7+7+ 22);
q9dot = State(7+8+ 22);
q10dot = State(7+9+ 22);
q11dot = State(7+10+ 22);
q12dot = State(7+11+ 22);
q13dot = State(7+12+ 22);
q14dot = State(7+13+ 22);
q15dot = State(7+14+ 22);
q16dot = State(7+15+ 22);

t2 = cos(alpha);
t3 = sin(alpha);
t4 = beta-q12;
t5 = sin(gamma);
t6 = cos(gamma);
t7 = sin(beta);
t8 = sin(t4);
t9 = cos(t4);
t10 = cos(beta);
t11 = t2.*t6.*t9.*2.68635e-3;
t12 = t2.*t5.*t9.*1.458538e-2;
t13 = t2.*t6.*8.71741e-3;
t14 = t2.*t5.*9.535293999999999e-2;
t15 = t3.*t5.*t7.*2.330279e-2;
t16 = t3.*t8.*1.065566e-2;
t17 = t2.*t5.*t7.*2.330279e-2;
rLeftHip = [rOx+t17-t3.*t5.*9.535293999999999e-2-t3.*t6.*8.71741e-3-t2.*t9.*1.065566e-2-t2.*t10.*3.172834e-2-t2.*t5.*t8.*1.458538e-2-t2.*t6.*t7.*9.266658999999999e-2-t2.*t6.*t8.*2.68635e-3;rOy+t13+t14+t15-t3.*t9.*1.065566e-2-t3.*t10.*3.172834e-2-t3.*t5.*t8.*1.458538e-2-t3.*t6.*t7.*9.266658999999999e-2-t3.*t6.*t8.*2.68635e-3;rOz+t7.*3.172834e-2+t8.*1.065566e-2-t5.*t9.*1.458538e-2+t5.*t10.*2.330279e-2-t6.*t9.*2.68635e-3-t6.*t10.*9.266658999999999e-2];
if nargout > 1
    t18 = t9.*1.065566e-2;
    t19 = t6.*t8.*2.68635e-3;
    t20 = t5.*t8.*1.458538e-2;
    vLeftHip = [rOxdot-betadot.*(t11+t12-t2.*t7.*3.172834e-2-t2.*t8.*1.065566e-2-t2.*t5.*t10.*2.330279e-2+t2.*t6.*t10.*9.266658999999999e-2)+q12dot.*(t11+t12-t2.*t8.*1.065566e-2)+alphadot.*(-t13-t14-t15+t3.*t9.*1.065566e-2+t3.*t10.*3.172834e-2+t3.*t5.*t8.*1.458538e-2+t3.*t6.*t7.*9.266658999999999e-2+t3.*t6.*t8.*2.68635e-3)+gammadot.*(t3.*t5.*8.71741e-3-t3.*t6.*9.535293999999999e-2+t2.*t5.*t7.*9.266658999999999e-2+t2.*t5.*t8.*2.68635e-3+t2.*t6.*t7.*2.330279e-2-t2.*t6.*t8.*1.458538e-2);rOydot+q12dot.*(-t16+t3.*t5.*t9.*1.458538e-2+t3.*t6.*t9.*2.68635e-3)-alphadot.*(-t17+t3.*t5.*9.535293999999999e-2+t3.*t6.*8.71741e-3+t2.*t9.*1.065566e-2+t2.*t10.*3.172834e-2+t2.*t5.*t8.*1.458538e-2+t2.*t6.*t7.*9.266658999999999e-2+t2.*t6.*t8.*2.68635e-3)+betadot.*(t16+t3.*t7.*3.172834e-2-t3.*t5.*t9.*1.458538e-2+t3.*t5.*t10.*2.330279e-2-t3.*t6.*t9.*2.68635e-3-t3.*t6.*t10.*9.266658999999999e-2)+gammadot.*(t2.*t5.*(-8.71741e-3)+t2.*t6.*9.535293999999999e-2+t3.*t5.*t7.*9.266658999999999e-2+t3.*t5.*t8.*2.68635e-3+t3.*t6.*t7.*2.330279e-2-t3.*t6.*t8.*1.458538e-2);rOzdot-q12dot.*(t18+t19+t20)+gammadot.*(t5.*t9.*2.68635e-3+t5.*t10.*9.266658999999999e-2-t6.*t9.*1.458538e-2+t6.*t10.*2.330279e-2)+betadot.*(t10.*3.172834e-2+t18+t19+t20-t5.*t7.*2.330279e-2+t6.*t7.*9.266658999999999e-2)];
end
if nargout > 2
    t21 = betadot-q12dot;
    omegaLeftHip = [gammadot-alphadot.*t8;t6.*t21+alphadot.*t5.*t9;-t5.*t21+alphadot.*t6.*t9];
end
if nargout > 3
    ILeftHip = reshape([5.0e-5,0.0,0.0,0.0,5.0e-5,0.0,0.0,0.0,5.0e-5],[3,3]);
end
if nargout > 4
    RLeftHip = reshape([t2.*t9,t3.*t9,-t8,-t3.*t6+t2.*t5.*t8,t2.*t6+t3.*t5.*t8,t5.*t9,t3.*t5+t2.*t6.*t8,-t2.*t5+t3.*t6.*t8,t6.*t9],[3,3]);
end
