function [rRightThigh,vRightThigh,omegaRightThigh,IRightThigh,RRightThigh] = autoGen_RightThigh(rOx,rOy,rOz,alpha,beta,gamma,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,rOxdot,rOydot,rOzdot,alphadot,betadot,gammadot,q1dot,q2dot,q3dot,q4dot,q5dot,q6dot,q7dot,q8dot,q9dot,q10dot,q11dot,q12dot,q13dot,q14dot,q15dot,q16dot)
%AUTOGEN_RIGHTTHIGH
%    [RRIGHTTHIGH,VRIGHTTHIGH,OMEGARIGHTTHIGH,IRIGHTTHIGH,RRIGHTTHIGH] = AUTOGEN_RIGHTTHIGH(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Oct-2018 20:28:56

t2 = sin(alpha);
t3 = cos(alpha);
t4 = beta-q4;
t5 = sin(gamma);
t6 = cos(gamma);
t7 = sin(t4);
t8 = gamma+q5;
t9 = sin(beta);
t10 = cos(t4);
t11 = sin(t8);
t12 = cos(beta);
t13 = cos(t8);
t14 = t2.*t10.*9.760599999999999e-3;
t15 = t3.*t11.*1.304877e-2;
t16 = t2.*t12.*3.172834e-2;
t17 = t3.*t5.*1.2766659e-1;
t18 = t2.*t5.*t9.*2.330279e-2;
t19 = t2.*t13.*1.304877e-2;
t20 = t3.*t7.*9.760599999999999e-3;
t21 = t3.*t10.*t13.*1.304877e-2;
t22 = t3.*t6.*t10.*(7.0./2.0e2);
t23 = t3.*t5.*t10.*3.225e-2;
t24 = t3.*t13.*1.304877e-2;
t25 = t2.*t7.*t11.*1.304877e-2;
t26 = t2.*t7.*9.760599999999999e-3;
t27 = t2.*t5.*t10.*3.225e-2;
t28 = t2.*t10.*t13.*1.304877e-2;
t29 = t2.*t6.*t10.*(7.0./2.0e2);
t30 = t3.*t10.*9.760599999999999e-3;
t31 = t3.*t12.*3.172834e-2;
t32 = t2.*t6.*8.94721e-3;
t33 = t3.*t5.*t9.*2.330279e-2;
rRightThigh = [rOx+t30+t31+t32+t33-t2.*t5.*1.2766659e-1-t2.*t11.*1.304877e-2-t3.*t5.*t7.*3.225e-2-t3.*t6.*t7.*(7.0./2.0e2)-t3.*t6.*t9.*9.266658999999999e-2-t3.*t7.*t13.*1.304877e-2;rOy+t14+t15+t16+t17+t18-t3.*t6.*8.94721e-3-t2.*t5.*t7.*3.225e-2-t2.*t6.*t7.*(7.0./2.0e2)-t2.*t6.*t9.*9.266658999999999e-2-t2.*t7.*t13.*1.304877e-2;rOz-t7.*9.760599999999999e-3-t9.*3.172834e-2-t5.*t10.*3.225e-2-t6.*t10.*(7.0./2.0e2)+t5.*t12.*2.330279e-2-t6.*t12.*9.266658999999999e-2-t10.*t13.*1.304877e-2];
if nargout > 1
    t34 = t7.*t13.*1.304877e-2;
    t35 = t6.*t7.*(7.0./2.0e2);
    t36 = t5.*t7.*3.225e-2;
    vRightThigh = [rOxdot-alphadot.*(t14+t15+t16+t17+t18-t3.*t6.*8.94721e-3-t2.*t5.*t7.*3.225e-2-t2.*t6.*t7.*(7.0./2.0e2)-t2.*t6.*t9.*9.266658999999999e-2-t2.*t7.*t13.*1.304877e-2)-gammadot.*(t19+t2.*t5.*8.94721e-3+t2.*t6.*1.2766659e-1-t3.*t5.*t7.*(7.0./2.0e2)+t3.*t6.*t7.*3.225e-2-t3.*t5.*t9.*9.266658999999999e-2-t3.*t6.*t9.*2.330279e-2-t3.*t7.*t11.*1.304877e-2)-q5dot.*(t19-t3.*t7.*t11.*1.304877e-2)-betadot.*(t20+t21+t22+t23+t3.*t9.*3.172834e-2-t3.*t5.*t12.*2.330279e-2+t3.*t6.*t12.*9.266658999999999e-2)+q4dot.*(t20+t21+t22+t23);rOydot+q5dot.*(t24+t25)-alphadot.*(-t30-t31-t32-t33+t2.*t5.*1.2766659e-1+t2.*t11.*1.304877e-2+t3.*t5.*t7.*3.225e-2+t3.*t6.*t7.*(7.0./2.0e2)+t3.*t6.*t9.*9.266658999999999e-2+t3.*t7.*t13.*1.304877e-2)+gammadot.*(t24+t25+t3.*t5.*8.94721e-3+t3.*t6.*1.2766659e-1+t2.*t5.*t7.*(7.0./2.0e2)-t2.*t6.*t7.*3.225e-2+t2.*t5.*t9.*9.266658999999999e-2+t2.*t6.*t9.*2.330279e-2)-betadot.*(t26+t27+t28+t29+t2.*t9.*3.172834e-2-t2.*t5.*t12.*2.330279e-2+t2.*t6.*t12.*9.266658999999999e-2)+q4dot.*(t26+t27+t28+t29);rOzdot+betadot.*(t10.*(-9.760599999999999e-3)-t12.*3.172834e-2+t34+t35+t36-t5.*t9.*2.330279e-2+t6.*t9.*9.266658999999999e-2)+gammadot.*(t5.*t10.*(7.0./2.0e2)-t6.*t10.*3.225e-2+t5.*t12.*9.266658999999999e-2+t6.*t12.*2.330279e-2+t10.*t11.*1.304877e-2)-q4dot.*(t10.*(-9.760599999999999e-3)+t34+t35+t36)+q5dot.*t10.*t11.*1.304877e-2];
end
if nargout > 2
    t37 = betadot-q4dot;
    omegaRightThigh = [gammadot+q5dot-alphadot.*t7;t13.*t37+alphadot.*t10.*t11;-t11.*t37+alphadot.*t10.*t13];
end
if nargout > 3
    IRightThigh = reshape([1.8e-5,0.0,0.0,0.0,3.0e-4,0.0,0.0,0.0,1.8e-5],[3,3]);
end
if nargout > 4
    RRightThigh = reshape([t3.*t10,t2.*t10,-t7,-t2.*t13+t3.*t7.*t11,t3.*t13+t2.*t7.*t11,t10.*t11,t2.*t11+t3.*t7.*t13,-t3.*t11+t2.*t7.*t13,t10.*t13],[3,3]);
end
