function [rBody,vBody,omegaBody,IBody,RBody] = autoGen_Body(rOx,rOy,rOz,alpha,beta,gamma,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,rOxdot,rOydot,rOzdot,alphadot,betadot,gammadot,q1dot,q2dot,q3dot,q4dot,q5dot,q6dot,q7dot,q8dot,q9dot,q10dot,q11dot,q12dot,q13dot,q14dot,q15dot,q16dot)
%AUTOGEN_BODY
%    [RBODY,VBODY,OMEGABODY,IBODY,RBODY] = AUTOGEN_BODY(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    28-Nov-2018 16:30:17

rBody = [rOx;rOy;rOz];
if nargout > 1
    vBody = [rOxdot;rOydot;rOzdot];
end
if nargout > 2
    t2 = sin(gamma);
    t3 = cos(gamma);
    t4 = sin(alpha);
    t5 = cos(alpha);
    t6 = sin(beta);
    t7 = cos(beta);
    t8 = betadot.*t3;
    t9 = alphadot.*t2.*t7;
    t10 = t8+t9;
    t11 = betadot.*t2;
    t15 = alphadot.*t3.*t7;
    t12 = t11-t15;
    t14 = alphadot.*t6;
    t13 = gammadot-t14;
    t16 = t3.*t4;
    t17 = t2.*t4;
    t18 = t3.*t5.*t6;
    t19 = t17+t18;
    t20 = t3.*t5;
    t21 = t2.*t4.*t6;
    t22 = t20+t21;
    t23 = t2.*t5;
    omegaBody = [-t12.*t19-t10.*(t16-t2.*t5.*t6)+t5.*t7.*t13;t10.*t22+t12.*(t23-t3.*t4.*t6)+t4.*t7.*t13;-t6.*t13+t2.*t7.*t10-t3.*t7.*t12];
end
if nargout > 3
    IBody = reshape([1.0./4.0e2,0.0,0.0,0.0,1.0./4.0e2,0.0,0.0,0.0,1.0./1.0e3],[3,3]);
end
if nargout > 4
    RBody = reshape([t5.*t7,t4.*t7,-t6,-t16+t2.*t5.*t6,t22,t2.*t7,t19,-t23+t3.*t4.*t6,t3.*t7],[3,3]);
end
