function [rRightHip,vRightHip,omegaRightHip,IRightHip,RRightHip] = autoGen_RightHip(rOx,rOy,rOz,alpha,beta,gamma,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,rOxdot,rOydot,rOzdot,alphadot,betadot,gammadot,q1dot,q2dot,q3dot,q4dot,q5dot,q6dot,q7dot,q8dot,q9dot,q10dot,q11dot,q12dot,q13dot,q14dot,q15dot,q16dot)
%AUTOGEN_RIGHTHIP
%    [RRIGHTHIP,VRIGHTHIP,OMEGARIGHTHIP,IRIGHTHIP,RRIGHTHIP] = AUTOGEN_RIGHTHIP(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    28-Nov-2018 16:31:26

t2 = sin(alpha);
t3 = sin(gamma);
t4 = t2.*t3;
t5 = cos(alpha);
t6 = cos(gamma);
t7 = sin(beta);
t8 = t5.*t6.*t7;
t9 = t4+t8;
t10 = cos(beta);
t11 = cos(q4);
t12 = sin(q4);
t13 = t3.*t5;
t15 = t2.*t6.*t7;
t14 = t13-t15;
t16 = t11.*t14.*2.68635e-3;
t17 = t5.*t6.*8.71741e-3;
t18 = t2.*t10.*3.172834e-2;
t19 = t3.*t5.*9.266658999999999e-2;
t20 = t2.*t10.*t11.*1.065566e-2;
t21 = t2.*t10.*t12.*2.68635e-3;
t22 = t2.*t3.*t7.*8.71741e-3;
t23 = t2.*t6;
t33 = t3.*t5.*t7;
t24 = t23-t33;
t25 = t9.*t12.*1.065566e-2;
t26 = t5.*t10.*3.172834e-2;
t27 = t5.*t10.*t11.*1.065566e-2;
t28 = t5.*t10.*t12.*2.68635e-3;
t29 = t3.*t5.*t7.*8.71741e-3;
rRightHip = [rOx+t25+t26+t27+t28+t29-t2.*t3.*9.266658999999999e-2-t2.*t6.*8.71741e-3-t9.*t11.*2.68635e-3-t5.*t6.*t7.*9.266658999999999e-2;rOy+t16+t17+t18+t19+t20+t21+t22-t12.*t14.*1.065566e-2-t2.*t6.*t7.*9.266658999999999e-2;rOz-t7.*3.172834e-2+t3.*t10.*8.71741e-3-t6.*t10.*9.266658999999999e-2-t7.*t11.*1.065566e-2-t7.*t12.*2.68635e-3-t6.*t10.*t11.*2.68635e-3+t6.*t10.*t12.*1.065566e-2];
if nargout > 1
    t30 = t5.*t6;
    t31 = t2.*t3.*t7;
    t32 = t30+t31;
    vRightHip = [rOxdot+q4dot.*(t9.*t11.*1.065566e-2+t9.*t12.*2.68635e-3+t5.*t10.*t11.*2.68635e-3-t5.*t10.*t12.*1.065566e-2)-alphadot.*(t16+t17+t18+t19+t20+t21+t22-t12.*t14.*1.065566e-2-t2.*t6.*t7.*9.266658999999999e-2)-betadot.*(t5.*t7.*3.172834e-2-t3.*t5.*t10.*8.71741e-3+t5.*t6.*t10.*9.266658999999999e-2+t5.*t7.*t11.*1.065566e-2+t5.*t7.*t12.*2.68635e-3+t5.*t6.*t10.*t11.*2.68635e-3-t5.*t6.*t10.*t12.*1.065566e-2)+gammadot.*(t2.*t3.*8.71741e-3-t2.*t6.*9.266658999999999e-2-t11.*t24.*2.68635e-3+t12.*t24.*1.065566e-2+t3.*t5.*t7.*9.266658999999999e-2+t5.*t6.*t7.*8.71741e-3);rOydot-q4dot.*(t11.*t14.*1.065566e-2+t12.*t14.*2.68635e-3-t2.*t10.*t11.*2.68635e-3+t2.*t10.*t12.*1.065566e-2)-betadot.*(t2.*t7.*3.172834e-2-t2.*t3.*t10.*8.71741e-3+t2.*t6.*t10.*9.266658999999999e-2+t2.*t7.*t11.*1.065566e-2+t2.*t7.*t12.*2.68635e-3+t2.*t6.*t10.*t11.*2.68635e-3-t2.*t6.*t10.*t12.*1.065566e-2)+gammadot.*(t3.*t5.*(-8.71741e-3)+t5.*t6.*9.266658999999999e-2+t11.*t32.*2.68635e-3-t12.*t32.*1.065566e-2+t2.*t3.*t7.*9.266658999999999e-2+t2.*t6.*t7.*8.71741e-3)+alphadot.*(t25+t26+t27+t28+t29-t2.*t3.*9.266658999999999e-2-t2.*t6.*8.71741e-3-t9.*t11.*2.68635e-3-t5.*t6.*t7.*9.266658999999999e-2);rOzdot+q4dot.*(t7.*t11.*(-2.68635e-3)+t7.*t12.*1.065566e-2+t6.*t10.*t11.*1.065566e-2+t6.*t10.*t12.*2.68635e-3)+gammadot.*(t3.*t10.*9.266658999999999e-2+t6.*t10.*8.71741e-3+t3.*t10.*t11.*2.68635e-3-t3.*t10.*t12.*1.065566e-2)-betadot.*(t10.*3.172834e-2+t3.*t7.*8.71741e-3-t6.*t7.*9.266658999999999e-2+t10.*t11.*1.065566e-2+t10.*t12.*2.68635e-3-t6.*t7.*t11.*2.68635e-3+t6.*t7.*t12.*1.065566e-2)];
end
if nargout > 2
    t34 = betadot.*t6;
    t35 = alphadot.*t3.*t10;
    t36 = t34+t35;
    t37 = betadot.*t3;
    t41 = alphadot.*t6.*t10;
    t38 = t37-t41;
    t40 = alphadot.*t7;
    t39 = gammadot-t40;
    omegaRightHip = [q4dot.*t24-t9.*t38-t24.*t36+t5.*t10.*t39;-q4dot.*t32+t14.*t38+t32.*t36+t2.*t10.*t39;-t7.*t39-q4dot.*t3.*t10+t3.*t10.*t36-t6.*t10.*t38];
end
if nargout > 3
    IRightHip = reshape([5.0e-5,0.0,0.0,0.0,5.0e-5,0.0,0.0,0.0,5.0e-5],[3,3]);
end
if nargout > 4
    RRightHip = reshape([t9.*t12+t5.*t10.*t11,-t12.*t14+t2.*t10.*t11,-t7.*t11+t6.*t10.*t12,-t23+t33,t32,t3.*t10,t9.*t11-t5.*t10.*t12,-t11.*t14-t2.*t10.*t12,t7.*t12+t6.*t10.*t11],[3,3]);
end
