function [rLeftArm,vLeftArm,omegaLeftArm,ILeftArm,RLeftArm] = autoGen_LeftArm(State)
%AUTOGEN_LEFTARM
%    [RLEFTARM,VLEFTARM,OMEGALEFTARM,ILEFTARM,RLEFTARM] = AUTOGEN_LEFTARM(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    24-Oct-2018 20:28:41

rOx = State(1);                 
rOy = State(2);
rOz = State(3);
alpha = State(4);
beta = State(5);
gamma = State(6);
q1 = State(7);
q2 = State(7+1);
q3 = State(7+2);
q4 = State(7+3);
q5 = State(7+4);
q6 = State(7+5);
q7 = State(7+6);
q8 = State(7+7);
q9 = State(7+8);
q10 = State(7+9);
q11 = State(7+10);
q12 = State(7+11);
q13 = State(7+12);
q14 = State(7+13);
q15 = State(7+14);
q16 = State(7+15);

rOxdot = State(1 + 22);                 
rOydot = State(2+ 22);
rOzdot = State(3+ 22);
alphadot = State(4+ 22);
betadot = State(5+ 22);
gammadot = State(6+ 22);
q1dot = State(7+ 22);
q2dot = State(7+1+ 22);
q3dot = State(7+2+ 22);
q4dot = State(7+3+ 22);
q5dot = State(7+4+ 22);
q6dot = State(7+5+ 22);
q7dot = State(7+6+ 22);
q8dot = State(7+7+ 22);
q9dot = State(7+8+ 22);
q10dot = State(7+9+ 22);
q11dot = State(7+10+ 22);
q12dot = State(7+11+ 22);
q13dot = State(7+12+ 22);
q14dot = State(7+13+ 22);
q15dot = State(7+14+ 22);
q16dot = State(7+15+ 22);

t2 = sin(alpha);
t3 = cos(alpha);
t4 = pi.*(1.0./1.8e1);
t5 = gamma-q1;
t6 = beta+t4;
t7 = sin(t5);
t8 = beta+q2+t4;
t9 = cos(gamma);
t10 = sin(beta);
t11 = sin(gamma);
t12 = cos(t6);
t13 = cos(t5);
t14 = cos(t8);
t15 = cos(beta);
t16 = sin(t6);
t17 = sin(t8);
t18 = t2.*t7.*t16.*2.575e-2;
t19 = t2.*t9.*t10.*3.18887e-2;
t20 = t3.*t17.*3.595415e-2;
t21 = t2.*t7.*4.667799999999986e-4;
t22 = t3.*t13.*t17.*2.621678e-2;
t23 = t2.*t11.*3.18887e-2;
t24 = t2.*t13.*4.667799999999986e-4;
t25 = t2.*t9.*1.64721e-3;
t26 = t3.*t7.*t16.*2.575e-2;
t27 = t3.*t9.*t10.*3.18887e-2;
rLeftArm = [rOx+t23+t24+t25+t26+t27-t3.*t12.*1.950677e-2-t3.*t14.*3.595415e-2-t3.*t15.*6.272722e-2-t3.*t10.*t11.*1.64721e-3-t3.*t7.*t17.*2.621678e-2;rOy+t18+t19-t3.*t9.*1.64721e-3-t2.*t12.*1.950677e-2-t3.*t11.*3.18887e-2-t2.*t14.*3.595415e-2-t3.*t13.*4.667799999999986e-4-t2.*t15.*6.272722e-2-t2.*t10.*t11.*1.64721e-3-t2.*t7.*t17.*2.621678e-2;rOz+t10.*6.272722e-2+t16.*1.950677e-2+t17.*3.595415e-2+t7.*t12.*2.575e-2-t7.*t14.*2.621678e-2+t9.*t15.*3.18887e-2-t11.*t15.*1.64721e-3];
if nargout > 1
    t28 = t2.*t17.*3.595415e-2;
    t29 = t2.*t13.*t17.*2.621678e-2;
    t30 = t12.*t13.*2.575e-2;
    t31 = t14.*3.595415e-2;
    t32 = t7.*t17.*2.621678e-2;
    vLeftArm = [rOxdot+betadot.*(t20+t3.*t10.*6.272722e-2+t3.*t16.*1.950677e-2+t3.*t7.*t12.*2.575e-2-t3.*t7.*t14.*2.621678e-2+t3.*t9.*t15.*3.18887e-2-t3.*t11.*t15.*1.64721e-3)-gammadot.*(t21+t22-t2.*t9.*3.18887e-2+t2.*t11.*1.64721e-3+t3.*t9.*t10.*1.64721e-3+t3.*t10.*t11.*3.18887e-2-t3.*t13.*t16.*2.575e-2)+q2dot.*(t20-t3.*t7.*t14.*2.621678e-2)+q1dot.*(t21+t22-t3.*t13.*t16.*2.575e-2)+alphadot.*(-t18-t19+t3.*t9.*1.64721e-3+t2.*t12.*1.950677e-2+t3.*t11.*3.18887e-2+t2.*t14.*3.595415e-2+t3.*t13.*4.667799999999986e-4+t2.*t15.*6.272722e-2+t2.*t10.*t11.*1.64721e-3+t2.*t7.*t17.*2.621678e-2);rOydot+betadot.*(t28+t2.*t10.*6.272722e-2+t2.*t16.*1.950677e-2+t2.*t7.*t12.*2.575e-2-t2.*t7.*t14.*2.621678e-2+t2.*t9.*t15.*3.18887e-2-t2.*t11.*t15.*1.64721e-3)-q1dot.*(-t29+t3.*t7.*4.667799999999986e-4+t2.*t13.*t16.*2.575e-2)+q2dot.*(t28-t2.*t7.*t14.*2.621678e-2)-gammadot.*(t29-t3.*t7.*4.667799999999986e-4+t3.*t9.*3.18887e-2-t3.*t11.*1.64721e-3+t2.*t9.*t10.*1.64721e-3+t2.*t10.*t11.*3.18887e-2-t2.*t13.*t16.*2.575e-2)+alphadot.*(t23+t24+t25+t26+t27-t3.*t12.*1.950677e-2-t3.*t14.*3.595415e-2-t3.*t15.*6.272722e-2-t3.*t10.*t11.*1.64721e-3-t3.*t7.*t17.*2.621678e-2);rOzdot+q2dot.*(t31+t32)-q1dot.*(t30-t13.*t14.*2.621678e-2)-gammadot.*(-t30+t9.*t15.*1.64721e-3+t11.*t15.*3.18887e-2+t13.*t14.*2.621678e-2)+betadot.*(t12.*1.950677e-2+t15.*6.272722e-2+t31+t32-t9.*t10.*3.18887e-2+t10.*t11.*1.64721e-3-t7.*t16.*2.575e-2)];
end
if nargout > 2
    t33 = betadot+q2dot;
    omegaLeftArm = [gammadot-q1dot-alphadot.*t17;t13.*t33+alphadot.*t7.*t14;-t7.*t33+alphadot.*t13.*t14];
end
if nargout > 3
    ILeftArm = reshape([3.515445e-5,0.0,0.0,0.0,1.25e-4,0.0,0.0,0.0,1.25e-4],[3,3]);
end
if nargout > 4
    RLeftArm = reshape([t3.*t14,t2.*t14,-t17,-t2.*t13+t3.*t7.*t17,t3.*t13+t2.*t7.*t17,t7.*t14,t2.*t7+t3.*t13.*t17,-t3.*t7+t2.*t13.*t17,t13.*t14],[3,3]);
end
