function [rLeftShoulder,vLeftShoulder,omegaLeftShoulder,ILeftShoulder,RLeftShoulder] = autoGen_LeftShoulder(rOx,rOy,rOz,alpha,beta,gamma,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,rOxdot,rOydot,rOzdot,alphadot,betadot,gammadot,q1dot,q2dot,q3dot,q4dot,q5dot,q6dot,q7dot,q8dot,q9dot,q10dot,q11dot,q12dot,q13dot,q14dot,q15dot,q16dot)
%AUTOGEN_LEFTSHOULDER
%    [RLEFTSHOULDER,VLEFTSHOULDER,OMEGALEFTSHOULDER,ILEFTSHOULDER,RLEFTSHOULDER] = AUTOGEN_LEFTSHOULDER(ROX,ROY,ROZ,ALPHA,BETA,GAMMA,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,ROXDOT,ROYDOT,ROZDOT,ALPHADOT,BETADOT,GAMMADOT,Q1DOT,Q2DOT,Q3DOT,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT,Q9DOT,Q10DOT,Q11DOT,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    28-Nov-2018 16:30:17

t2 = sin(alpha);
t3 = cos(alpha);
t4 = cos(gamma);
t5 = sin(beta);
t6 = sin(gamma);
t7 = cos(beta);
t8 = t2.*t4.*t5.*3.262337244655502e-2;
t9 = t2.*t6.*3.262337244655502e-2;
t10 = t2.*t4.*1.64721e-3;
t11 = t3.*t4.*t5.*3.262337244655502e-2;
rLeftShoulder = [rOx+t9+t10+t11-t3.*t7.*6.689375448952158e-2-t3.*t5.*t6.*1.64721e-3;rOy+t8-t3.*t4.*1.64721e-3-t2.*t7.*6.689375448952158e-2-t3.*t6.*3.262337244655502e-2-t2.*t5.*t6.*1.64721e-3;rOz+t5.*6.689375448952158e-2+t4.*t7.*3.262337244655502e-2-t6.*t7.*1.64721e-3];
if nargout > 1
    vLeftShoulder = [rOxdot+alphadot.*(-t8+t3.*t4.*1.64721e-3+t2.*t7.*6.689375448952158e-2+t3.*t6.*3.262337244655502e-2+t2.*t5.*t6.*1.64721e-3)-gammadot.*(t2.*t4.*(-3.262337244655502e-2)+t2.*t6.*1.64721e-3+t3.*t4.*t5.*1.64721e-3+t3.*t5.*t6.*3.262337244655502e-2)+betadot.*(t3.*t5.*6.689375448952158e-2+t3.*t4.*t7.*3.262337244655502e-2-t3.*t6.*t7.*1.64721e-3);rOydot+alphadot.*(t9+t10+t11-t3.*t7.*6.689375448952158e-2-t3.*t5.*t6.*1.64721e-3)-gammadot.*(t3.*t4.*3.262337244655502e-2-t3.*t6.*1.64721e-3+t2.*t4.*t5.*1.64721e-3+t2.*t5.*t6.*3.262337244655502e-2)+betadot.*(t2.*t5.*6.689375448952158e-2+t2.*t4.*t7.*3.262337244655502e-2-t2.*t6.*t7.*1.64721e-3);rOzdot-gammadot.*(t4.*t7.*1.64721e-3+t6.*t7.*3.262337244655502e-2)+betadot.*(t7.*6.689375448952158e-2-t4.*t5.*3.262337244655502e-2+t5.*t6.*1.64721e-3)];
end
if nargout > 2
    t12 = betadot.*t4;
    t13 = alphadot.*t6.*t7;
    t14 = t12+t13;
    t15 = betadot.*t6;
    t19 = alphadot.*t4.*t7;
    t16 = t15-t19;
    t18 = alphadot.*t5;
    t17 = gammadot-t18;
    t20 = t2.*t6.*1.736481776669303e-1;
    t21 = t3.*t4.*t5.*1.736481776669303e-1;
    t22 = t2.*t4;
    t25 = t3.*t5.*t6;
    t23 = t22-t25;
    t24 = sin(q1);
    t26 = cos(q1);
    t27 = t2.*t6.*9.84807753012208e-1;
    t28 = t3.*t7.*1.736481776669303e-1;
    t29 = t3.*t4.*t5.*9.84807753012208e-1;
    t30 = t27+t28+t29;
    t31 = t2.*t7.*9.84807753012208e-1;
    t32 = t3.*t6.*1.736481776669303e-1;
    t33 = t31+t32-t2.*t4.*t5.*1.736481776669303e-1;
    t34 = t3.*t4;
    t35 = t2.*t5.*t6;
    t36 = t34+t35;
    t37 = t2.*t7.*1.736481776669303e-1;
    t38 = t2.*t4.*t5.*9.84807753012208e-1;
    t39 = t37+t38-t3.*t6.*9.84807753012208e-1;
    t40 = t5.*9.84807753012208e-1;
    t41 = t4.*t7.*1.736481776669303e-1;
    omegaLeftShoulder = [-t16.*(t2.*t6+t3.*t4.*t5)-t14.*t23+q1dot.*(t20+t21-t3.*t7.*9.84807753012208e-1)+t3.*t7.*t17;t16.*(t3.*t6-t2.*t4.*t5)-q1dot.*t33+t14.*t36+t2.*t7.*t17;q1dot.*(t40+t41)-t5.*t17-t4.*t7.*t16+t6.*t7.*t14];
end
if nargout > 3
    ILeftShoulder = reshape([3.6e-6,0.0,0.0,0.0,7.698e-7,0.0,0.0,0.0,3.6e-6],[3,3]);
end
if nargout > 4
    t42 = t5.*1.736481776669303e-1;
    t43 = t42-t4.*t7.*9.84807753012208e-1;
    RLeftShoulder = reshape([-t20-t21+t3.*t7.*9.84807753012208e-1,t33,-t40-t41,-t23.*t26-t24.*t30,t26.*t36-t24.*t39,t24.*t43+t6.*t7.*t26,-t23.*t24+t26.*t30,t24.*t36+t26.*t39,-t26.*t43+t6.*t7.*t24],[3,3]);
end
