function omegaRightArm = omegaRightArm_fn(alphadot,betadot,beta,gammadot,gamma,q9,q10,q10dot,q9dot)
%OMEGARIGHTARM_FN
%    OMEGARIGHTARM = OMEGARIGHTARM_FN(ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q9,Q10,Q10DOT,Q9DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Oct-2018 14:57:20

t6 = pi.*(1.0./1.8e1);
t2 = beta+q10-t6;
t3 = gamma+q9;
t4 = sin(t3);
t5 = betadot+q10dot;
t7 = cos(t2);
t8 = cos(t3);
omegaRightArm = [gammadot+q9dot-alphadot.*sin(t2);t5.*t8+alphadot.*t4.*t7;-t4.*t5+alphadot.*t7.*t8];
