function omegaLeftHand = omegaLeftHand_fn(alphadot,betadot,beta,gammadot,gamma,q1,q2,q3,q1dot,q2dot,q3dot)
%OMEGALEFTHAND_FN
%    OMEGALEFTHAND = OMEGALEFTHAND_FN(ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q1,Q2,Q3,Q1DOT,Q2DOT,Q3DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Oct-2018 14:57:19

t2 = gamma-q1;
t3 = pi.*(1.0./1.8e1);
t4 = beta+q2+q3+t3;
t5 = sin(t2);
t6 = betadot+q2dot+q3dot;
t7 = cos(t4);
t8 = cos(t2);
omegaLeftHand = [gammadot-q1dot-alphadot.*sin(t4);t6.*t8+alphadot.*t5.*t7;-t5.*t6+alphadot.*t7.*t8];
