function omegaRightShoulder = omegaRightShoulder_fn(alphadot,betadot,beta,gammadot,gamma,q9,q9dot)
%OMEGARIGHTSHOULDER_FN
%    OMEGARIGHTSHOULDER = OMEGARIGHTSHOULDER_FN(ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q9,Q9DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Oct-2018 14:57:19

t2 = gamma+q9;
t6 = pi.*(1.0./1.8e1);
t3 = beta-t6;
t4 = sin(t2);
t5 = cos(t2);
t7 = cos(t3);
omegaRightShoulder = [gammadot+q9dot-alphadot.*sin(t3);betadot.*t5+alphadot.*t4.*t7;-betadot.*t4+alphadot.*t5.*t7];
