function omegaLeftArm = omegaLeftArm_fn(alphadot,betadot,beta,gammadot,gamma,q1,q2,q1dot,q2dot)
%OMEGALEFTARM_FN
%    OMEGALEFTARM = OMEGALEFTARM_FN(ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q1,Q2,Q1DOT,Q2DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Oct-2018 14:57:19

t2 = gamma-q1;
t3 = pi.*(1.0./1.8e1);
t4 = beta+q2+t3;
t5 = sin(t2);
t6 = betadot+q2dot;
t7 = cos(t4);
t8 = cos(t2);
omegaLeftArm = [gammadot-q1dot-alphadot.*sin(t4);t6.*t8+alphadot.*t5.*t7;-t5.*t6+alphadot.*t7.*t8];
