function omegaLeftShoulder = omegaLeftShoulder_fn(alphadot,betadot,beta,gammadot,gamma,q1,q1dot)
%OMEGALEFTSHOULDER_FN
%    OMEGALEFTSHOULDER = OMEGALEFTSHOULDER_FN(ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q1,Q1DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Oct-2018 14:57:19

t2 = gamma-q1;
t3 = pi.*(1.0./1.8e1);
t4 = beta+t3;
t5 = sin(t2);
t6 = cos(t4);
t7 = cos(t2);
omegaLeftShoulder = [gammadot-q1dot-alphadot.*sin(t4);betadot.*t7+alphadot.*t5.*t6;-betadot.*t5+alphadot.*t6.*t7];
