function omegaRightHip = omegaRightHip_fn(alphadot,betadot,beta,gammadot,gamma,q4,q4dot)
%OMEGARIGHTHIP_FN
%    OMEGARIGHTHIP = OMEGARIGHTHIP_FN(ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q4,Q4DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Oct-2018 14:57:21

t2 = beta-q4;
t3 = sin(gamma);
t4 = betadot-q4dot;
t5 = cos(gamma);
t6 = cos(t2);
omegaRightHip = [gammadot-alphadot.*sin(t2);t4.*t5+alphadot.*t3.*t6;-t3.*t4+alphadot.*t5.*t6];
