function omegaLeftThigh = omegaLeftThigh_fn(alphadot,betadot,beta,gammadot,gamma,q12,q13,q12dot,q13dot)
%OMEGALEFTTHIGH_FN
%    OMEGALEFTTHIGH = OMEGALEFTTHIGH_FN(ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q12,Q13,Q12DOT,Q13DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Oct-2018 14:57:20

t2 = gamma-q13;
t3 = beta-q12;
t4 = sin(t2);
t5 = betadot-q12dot;
t6 = cos(t3);
t7 = cos(t2);
omegaLeftThigh = [gammadot-q13dot-alphadot.*sin(t3);t5.*t7+alphadot.*t4.*t6;-t4.*t5+alphadot.*t6.*t7];
