function omegaLeftAnkle = omegaLeftAnkle_fn(alphadot,betadot,beta,gammadot,gamma,q12,q13,q14,q15,q12dot,q13dot,q14dot,q15dot)
%OMEGALEFTANKLE_FN
%    OMEGALEFTANKLE = OMEGALEFTANKLE_FN(ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q12,Q13,Q14,Q15,Q12DOT,Q13DOT,Q14DOT,Q15DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Oct-2018 14:57:21

t2 = -gamma+q13+q14+q15;
t3 = beta-q12;
t4 = sin(t2);
t5 = betadot-q12dot;
t6 = cos(t2);
t7 = cos(t3);
omegaLeftAnkle = [gammadot-q13dot-q14dot-q15dot-alphadot.*sin(t3);t5.*t6-alphadot.*t4.*t7;t4.*t5+alphadot.*t6.*t7];
