function omegaRightFoot = omegaRightFoot_fn(alphadot,betadot,beta,gammadot,gamma,q4,q5,q6,q7,q8,q4dot,q5dot,q6dot,q7dot,q8dot)
%OMEGARIGHTFOOT_FN
%    OMEGARIGHTFOOT = OMEGARIGHTFOOT_FN(ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q4,Q5,Q6,Q7,Q8,Q4DOT,Q5DOT,Q6DOT,Q7DOT,Q8DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Oct-2018 14:57:22

t2 = beta-q4+q8;
t3 = gamma+q5+q6-q7;
t4 = sin(t3);
t5 = betadot-q4dot+q8dot;
t6 = cos(t2);
t7 = cos(t3);
omegaRightFoot = [gammadot+q5dot+q6dot-q7dot-alphadot.*sin(t2);t5.*t7+alphadot.*t4.*t6;-t4.*t5+alphadot.*t6.*t7];
