function omegaBody = omegaBody_fn(alphadot,betadot,beta,gammadot,gamma)
%OMEGABODY_FN
%    OMEGABODY = OMEGABODY_FN(ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Oct-2018 14:57:18

t2 = sin(gamma);
t3 = cos(beta);
t4 = cos(gamma);
omegaBody = [gammadot-alphadot.*sin(beta);betadot.*t4+alphadot.*t2.*t3;-betadot.*t2+alphadot.*t3.*t4];
