function omegaLeftFoot = omegaLeftFoot_fn(alphadot,betadot,beta,gammadot,gamma,q12,q13,q14,q15,q16,q12dot,q13dot,q14dot,q15dot,q16dot)
%OMEGALEFTFOOT_FN
%    OMEGALEFTFOOT = OMEGALEFTFOOT_FN(ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q12,Q13,Q14,Q15,Q16,Q12DOT,Q13DOT,Q14DOT,Q15DOT,Q16DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Oct-2018 14:57:21

t2 = beta-q12+q16;
t3 = -gamma+q13+q14+q15;
t4 = sin(t3);
t5 = betadot-q12dot+q16dot;
t6 = cos(t2);
t7 = cos(t3);
omegaLeftFoot = [gammadot-q13dot-q14dot-q15dot-alphadot.*sin(t2);t5.*t7-alphadot.*t4.*t6;t4.*t5+alphadot.*t6.*t7];
