function rBody = rBody_fn(rOx,rOy,rOz)
%RBODY_FN
%    RBODY = RBODY_FN(ROX,ROY,ROZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:06

rBody = [rOx;rOy;rOz];
