function rLeftHip = rLeftHip_fn(alpha,beta,gamma,q12,rOx,rOy,rOz)
%RLEFTHIP_FN
%    RLEFTHIP = RLEFTHIP_FN(ALPHA,BETA,GAMMA,Q12,ROX,ROY,ROZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:08

t2 = cos(alpha);
t3 = sin(alpha);
t4 = beta-q12;
t5 = sin(gamma);
t6 = cos(gamma);
t7 = sin(beta);
t8 = sin(t4);
t9 = cos(t4);
t10 = cos(beta);
rLeftHip = [rOx-t3.*t5.*9.535293999999999e-2-t3.*t6.*8.71741e-3-t2.*t9.*1.065566e-2-t2.*t10.*3.172834e-2+t2.*t5.*t7.*2.330279e-2-t2.*t5.*t8.*1.458538e-2-t2.*t6.*t7.*9.266658999999999e-2-t2.*t6.*t8.*2.68635e-3;rOy+t2.*t5.*9.535293999999999e-2+t2.*t6.*8.71741e-3-t3.*t9.*1.065566e-2-t3.*t10.*3.172834e-2+t3.*t5.*t7.*2.330279e-2-t3.*t5.*t8.*1.458538e-2-t3.*t6.*t7.*9.266658999999999e-2-t3.*t6.*t8.*2.68635e-3;rOz+t7.*3.172834e-2+t8.*1.065566e-2-t5.*t9.*1.458538e-2+t5.*t10.*2.330279e-2-t6.*t9.*2.68635e-3-t6.*t10.*9.266658999999999e-2];
