function rLeftArm = rLeftArm_fn(alpha,beta,gamma,q1,q2,rOx,rOy,rOz)
%RLEFTARM_FN
%    RLEFTARM = RLEFTARM_FN(ALPHA,BETA,GAMMA,Q1,Q2,ROX,ROY,ROZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:07

t2 = sin(alpha);
t3 = cos(alpha);
t4 = pi.*(1.0./1.8e1);
t5 = gamma-q1;
t6 = beta+t4;
t7 = sin(t5);
t8 = beta+q2+t4;
t9 = cos(gamma);
t10 = sin(beta);
t11 = sin(gamma);
t12 = cos(t6);
t13 = cos(t5);
t14 = cos(t8);
t15 = cos(beta);
t16 = sin(t6);
t17 = sin(t8);
rLeftArm = [rOx+t2.*t9.*1.64721e-3+t2.*t11.*3.18887e-2+t2.*t13.*4.667799999999986e-4-t3.*t12.*1.950677e-2-t3.*t14.*3.595415e-2-t3.*t15.*6.272722e-2+t3.*t9.*t10.*3.18887e-2-t3.*t10.*t11.*1.64721e-3+t3.*t7.*t16.*2.575e-2-t3.*t7.*t17.*2.621678e-2;rOy-t3.*t9.*1.64721e-3-t2.*t12.*1.950677e-2-t3.*t11.*3.18887e-2-t2.*t14.*3.595415e-2-t3.*t13.*4.667799999999986e-4-t2.*t15.*6.272722e-2+t2.*t9.*t10.*3.18887e-2-t2.*t10.*t11.*1.64721e-3+t2.*t7.*t16.*2.575e-2-t2.*t7.*t17.*2.621678e-2;rOz+t10.*6.272722e-2+t16.*1.950677e-2+t17.*3.595415e-2+t7.*t12.*2.575e-2-t7.*t14.*2.621678e-2+t9.*t15.*3.18887e-2-t11.*t15.*1.64721e-3];
