function rLeftThigh = rLeftThigh_fn(alpha,beta,gamma,q12,q13,rOx,rOy,rOz)
%RLEFTTHIGH_FN
%    RLEFTTHIGH = RLEFTTHIGH_FN(ALPHA,BETA,GAMMA,Q12,Q13,ROX,ROY,ROZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:08

t2 = sin(alpha);
t3 = cos(alpha);
t4 = beta-q12;
t5 = sin(gamma);
t6 = sin(t4);
t7 = gamma-q13;
t8 = cos(gamma);
t9 = sin(beta);
t10 = cos(t4);
t11 = sin(t7);
t12 = cos(beta);
t13 = cos(t7);
rLeftThigh = [rOx-t2.*t5.*1.2766659e-1+t2.*t8.*8.94721e-3-t2.*t11.*1.304877e-2-t3.*t10.*9.760599999999999e-3-t3.*t12.*3.172834e-2-t3.*t5.*t6.*3.225e-2+t3.*t5.*t9.*2.330279e-2-t3.*t6.*t8.*(7.0./2.0e2)-t3.*t8.*t9.*9.266658999999999e-2-t3.*t6.*t13.*1.304877e-2;rOy+t3.*t5.*1.2766659e-1-t3.*t8.*8.94721e-3-t2.*t10.*9.760599999999999e-3-t2.*t12.*3.172834e-2+t3.*t11.*1.304877e-2-t2.*t5.*t6.*3.225e-2+t2.*t5.*t9.*2.330279e-2-t2.*t6.*t8.*(7.0./2.0e2)-t2.*t8.*t9.*9.266658999999999e-2-t2.*t6.*t13.*1.304877e-2;rOz+t6.*9.760599999999999e-3+t9.*3.172834e-2-t5.*t10.*3.225e-2+t5.*t12.*2.330279e-2-t8.*t10.*(7.0./2.0e2)-t8.*t12.*9.266658999999999e-2-t10.*t13.*1.304877e-2];
