function RLeftThigh = RotLeftThigh_fn(alpha,beta,gamma,q12,q13)
%ROTLEFTTHIGH_FN
%    RLEFTTHIGH = ROTLEFTTHIGH_FN(ALPHA,BETA,GAMMA,Q12,Q13)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:23

t2 = beta-q12;
t3 = gamma-q13;
t4 = cos(alpha);
t5 = sin(t3);
t6 = sin(alpha);
t7 = sin(t2);
t8 = cos(t3);
t9 = cos(t2);
RLeftThigh = reshape([t4.*t9,t6.*t9,-t7,-t6.*t8+t4.*t5.*t7,t4.*t8+t5.*t6.*t7,t5.*t9,t5.*t6+t4.*t7.*t8,-t4.*t5+t6.*t7.*t8,t8.*t9],[3,3]);
