function RLeftAnkle = RotLeftAnkle_fn(alpha,beta,gamma,q12,q13,q14,q15)
%ROTLEFTANKLE_FN
%    RLEFTANKLE = ROTLEFTANKLE_FN(ALPHA,BETA,GAMMA,Q12,Q13,Q14,Q15)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:23

t2 = beta-q12;
t3 = cos(alpha);
t4 = -gamma+q13+q14+q15;
t5 = sin(alpha);
t6 = sin(t4);
t7 = sin(t2);
t8 = cos(t4);
t9 = cos(t2);
RLeftAnkle = reshape([t3.*t9,t5.*t9,-t7,-t5.*t8-t3.*t6.*t7,t3.*t8-t5.*t6.*t7,-t6.*t9,-t5.*t6+t3.*t7.*t8,t3.*t6+t5.*t7.*t8,t8.*t9],[3,3]);
