function RLeftHand = RotLeftHand_fn(alpha,beta,gamma,q1,q2,q3)
%ROTLEFTHAND_FN
%    RLEFTHAND = ROTLEFTHAND_FN(ALPHA,BETA,GAMMA,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:22

t2 = gamma-q1;
t3 = cos(alpha);
t4 = pi.*(1.0./1.8e1);
t5 = beta+q2+q3+t4;
t6 = sin(t2);
t7 = sin(alpha);
t8 = sin(t5);
t9 = cos(t2);
t10 = cos(t5);
RLeftHand = reshape([t3.*t10,t7.*t10,-t8,-t7.*t9+t3.*t6.*t8,t3.*t9+t6.*t7.*t8,t6.*t10,t6.*t7+t3.*t8.*t9,-t3.*t6+t7.*t8.*t9,t9.*t10],[3,3]);
