function RRightHip = RotRightHip_fn(alpha,beta,gamma,q4)
%ROTRIGHTHIP_FN
%    RRIGHTHIP = ROTRIGHTHIP_FN(ALPHA,BETA,GAMMA,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:23

t2 = beta-q4;
t3 = cos(alpha);
t4 = sin(alpha);
t5 = sin(gamma);
t6 = sin(t2);
t7 = cos(gamma);
t8 = cos(t2);
RRightHip = reshape([t3.*t8,t4.*t8,-t6,-t4.*t7+t3.*t5.*t6,t3.*t7+t4.*t5.*t6,t5.*t8,t4.*t5+t3.*t6.*t7,-t3.*t5+t4.*t6.*t7,t7.*t8],[3,3]);
