function RRightThigh = RotRightThigh_fn(alpha,beta,gamma,q4,q5)
%ROTRIGHTTHIGH_FN
%    RRIGHTTHIGH = ROTRIGHTTHIGH_FN(ALPHA,BETA,GAMMA,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:24

t2 = beta-q4;
t3 = gamma+q5;
t4 = cos(alpha);
t5 = sin(t3);
t6 = sin(alpha);
t7 = sin(t2);
t8 = cos(t3);
t9 = cos(t2);
RRightThigh = reshape([t4.*t9,t6.*t9,-t7,-t6.*t8+t4.*t5.*t7,t4.*t8+t5.*t6.*t7,t5.*t9,t5.*t6+t4.*t7.*t8,-t4.*t5+t6.*t7.*t8,t8.*t9],[3,3]);
