function RRightArm = RotRightArm_fn(alpha,beta,gamma,q9,q10)
%ROTRIGHTARM_FN
%    RRIGHTARM = ROTRIGHTARM_FN(ALPHA,BETA,GAMMA,Q9,Q10)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:22

t7 = pi.*(1.0./1.8e1);
t2 = beta+q10-t7;
t3 = gamma+q9;
t4 = cos(alpha);
t5 = sin(t3);
t6 = sin(alpha);
t8 = sin(t2);
t9 = cos(t3);
t10 = cos(t2);
RRightArm = reshape([t4.*t10,t6.*t10,-t8,-t6.*t9+t4.*t5.*t8,t4.*t9+t5.*t6.*t8,t5.*t10,t5.*t6+t4.*t8.*t9,-t4.*t5+t6.*t8.*t9,t9.*t10],[3,3]);
