function RRightShoulder = RotRightShoulder_fn(alpha,beta,gamma,q9)
%ROTRIGHTSHOULDER_FN
%    RRIGHTSHOULDER = ROTRIGHTSHOULDER_FN(ALPHA,BETA,GAMMA,Q9)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:22

t2 = gamma+q9;
t3 = cos(alpha);
t8 = pi.*(1.0./1.8e1);
t4 = beta-t8;
t5 = sin(t2);
t6 = sin(alpha);
t7 = cos(t2);
t9 = sin(t4);
t10 = cos(t4);
RRightShoulder = reshape([t3.*t10,t6.*t10,-t9,-t6.*t7+t3.*t5.*t9,t3.*t7+t5.*t6.*t9,t5.*t10,t5.*t6+t3.*t7.*t9,-t3.*t5+t6.*t7.*t9,t7.*t10],[3,3]);
