function rRightHand = rRightHand_fn(alpha,beta,gamma,q9,q10,q11,rOx,rOy,rOz)
%RRIGHTHAND_FN
%    RRIGHTHAND = RRIGHTHAND_FN(ALPHA,BETA,GAMMA,Q9,Q10,Q11,ROX,ROY,ROZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:07

t2 = sin(alpha);
t3 = cos(alpha);
t4 = gamma+q9;
t7 = pi.*(1.0./1.8e1);
t5 = beta+q10+q11-t7;
t6 = sin(t4);
t8 = cos(gamma);
t9 = sin(beta);
t10 = sin(gamma);
t11 = beta-t7;
t12 = cos(t4);
t13 = cos(t5);
t14 = cos(beta);
t15 = sin(t5);
t16 = sin(t11);
t17 = beta+q10-t7;
t18 = cos(t11);
rRightHand = [rOx+t3.*cos(beta+q10-pi.*(1.0./1.8e1)).*(9.0./1.25e2)+t2.*t8.*1.64721e-3+t2.*t10.*3.18887e-2+t2.*t12.*3.93937e-3+t3.*t13.*4.614073e-2+t3.*t14.*6.272722e-2+t3.*cos(beta-pi.*(1.0./1.8e1)).*1.950677e-2+t3.*t8.*t9.*3.18887e-2-t3.*t9.*t10.*1.64721e-3-t3.*t6.*t15.*2.968937e-2+t3.*t6.*t16.*2.575e-2;rOy-t3.*t8.*1.64721e-3-t3.*t10.*3.18887e-2+t2.*t13.*4.614073e-2-t3.*t12.*3.93937e-3+t2.*t14.*6.272722e-2+t2.*t18.*1.950677e-2+t2.*cos(t17).*(9.0./1.25e2)+t2.*t8.*t9.*3.18887e-2-t2.*t9.*t10.*1.64721e-3-t2.*t6.*t15.*2.968937e-2+t2.*t6.*t16.*2.575e-2;rOz-t9.*6.272722e-2-t15.*4.614073e-2-t16.*1.950677e-2-sin(t17).*(9.0./1.25e2)-t6.*t13.*2.968937e-2+t8.*t14.*3.18887e-2+t6.*t18.*2.575e-2-t10.*t14.*1.64721e-3];
