function rRightShoulder = rRightShoulder_fn(alpha,beta,gamma,rOx,rOy,rOz)
%RRIGHTSHOULDER_FN
%    RRIGHTSHOULDER = RRIGHTSHOULDER_FN(ALPHA,BETA,GAMMA,ROX,ROY,ROZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:07

t2 = cos(alpha);
t3 = sin(alpha);
t4 = cos(gamma);
t5 = sin(beta);
t6 = sin(gamma);
t10 = pi.*(1.0./1.8e1);
t7 = beta-t10;
t8 = cos(t7);
t9 = cos(beta);
rRightShoulder = [rOx+t3.*t4.*1.64721e-3+t3.*t6.*3.18887e-2+t2.*t8.*4.23081e-3+t2.*t9.*6.272722e-2+t2.*t4.*t5.*3.18887e-2-t2.*t5.*t6.*1.64721e-3;rOy-t2.*t4.*1.64721e-3-t2.*t6.*3.18887e-2+t3.*t8.*4.23081e-3+t3.*t9.*6.272722e-2+t3.*t4.*t5.*3.18887e-2-t3.*t5.*t6.*1.64721e-3;rOz-t5.*6.272722e-2-sin(t7).*4.23081e-3+t4.*t9.*3.18887e-2-t6.*t9.*1.64721e-3];
