function rRightShank = rRightShank_fn(alpha,beta,gamma,q4,q5,q6,rOx,rOy,rOz)
%RRIGHTSHANK_FN
%    RRIGHTSHANK = RRIGHTSHANK_FN(ALPHA,BETA,GAMMA,Q4,Q5,Q6,ROX,ROY,ROZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:09

t2 = sin(alpha);
t3 = cos(alpha);
t4 = beta-q4;
t5 = sin(gamma);
t6 = sin(t4);
t7 = gamma+q5+q6;
t8 = cos(gamma);
t9 = gamma+q5;
t10 = sin(beta);
t11 = cos(t4);
t12 = sin(t7);
t13 = sin(t9);
t14 = cos(beta);
t15 = cos(t7);
t16 = cos(t9);
rRightShank = [rOx-t2.*t5.*1.2766659e-1+t2.*t8.*8.94721e-3-t2.*t12.*3.29934e-2+t3.*t11.*1.088657e-2-t2.*t13.*5.55e-2+t3.*t14.*3.172834e-2-t3.*t5.*t6.*3.225e-2-t3.*t6.*t8.*(7.0./2.0e2)+t3.*t5.*t10.*2.330279e-2-t3.*t8.*t10.*9.266658999999999e-2-t3.*t6.*t15.*3.29934e-2-t3.*t6.*t16.*5.55e-2;rOy+t3.*t5.*1.2766659e-1-t3.*t8.*8.94721e-3+t2.*t11.*1.088657e-2+t3.*t12.*3.29934e-2+t2.*t14.*3.172834e-2+t3.*t13.*5.55e-2-t2.*t5.*t6.*3.225e-2-t2.*t6.*t8.*(7.0./2.0e2)+t2.*t5.*t10.*2.330279e-2-t2.*t8.*t10.*9.266658999999999e-2-t2.*t6.*t15.*3.29934e-2-t2.*t6.*t16.*5.55e-2;rOz-t6.*1.088657e-2-t10.*3.172834e-2-t5.*t11.*3.225e-2+t5.*t14.*2.330279e-2-t8.*t11.*(7.0./2.0e2)-t8.*t14.*9.266658999999999e-2-t11.*t15.*3.29934e-2-t11.*t16.*5.55e-2];
