function rRightThigh = rRightThigh_fn(alpha,beta,gamma,q4,q5,rOx,rOy,rOz)
%RRIGHTTHIGH_FN
%    RRIGHTTHIGH = RRIGHTTHIGH_FN(ALPHA,BETA,GAMMA,Q4,Q5,ROX,ROY,ROZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:09

t2 = sin(alpha);
t3 = cos(alpha);
t4 = beta-q4;
t5 = sin(gamma);
t6 = cos(gamma);
t7 = sin(t4);
t8 = gamma+q5;
t9 = sin(beta);
t10 = cos(t4);
t11 = sin(t8);
t12 = cos(beta);
t13 = cos(t8);
rRightThigh = [rOx-t2.*t5.*1.2766659e-1+t2.*t6.*8.94721e-3-t2.*t11.*1.304877e-2+t3.*t10.*9.760599999999999e-3+t3.*t12.*3.172834e-2-t3.*t5.*t7.*3.225e-2-t3.*t6.*t7.*(7.0./2.0e2)+t3.*t5.*t9.*2.330279e-2-t3.*t6.*t9.*9.266658999999999e-2-t3.*t7.*t13.*1.304877e-2;rOy+t3.*t5.*1.2766659e-1-t3.*t6.*8.94721e-3+t2.*t10.*9.760599999999999e-3+t2.*t12.*3.172834e-2+t3.*t11.*1.304877e-2-t2.*t5.*t7.*3.225e-2-t2.*t6.*t7.*(7.0./2.0e2)+t2.*t5.*t9.*2.330279e-2-t2.*t6.*t9.*9.266658999999999e-2-t2.*t7.*t13.*1.304877e-2;rOz-t7.*9.760599999999999e-3-t9.*3.172834e-2-t5.*t10.*3.225e-2-t6.*t10.*(7.0./2.0e2)+t5.*t12.*2.330279e-2-t6.*t12.*9.266658999999999e-2-t10.*t13.*1.304877e-2];
