function rRightArm = rRightArm_fn(alpha,beta,gamma,q9,q10,rOx,rOy,rOz)
%RRIGHTARM_FN
%    RRIGHTARM = RRIGHTARM_FN(ALPHA,BETA,GAMMA,Q9,Q10,ROX,ROY,ROZ)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:07

t2 = sin(alpha);
t3 = cos(alpha);
t7 = pi.*(1.0./1.8e1);
t4 = beta+q10-t7;
t5 = gamma+q9;
t6 = sin(t5);
t8 = cos(gamma);
t9 = sin(beta);
t10 = sin(gamma);
t11 = beta-t7;
t12 = cos(t4);
t13 = cos(t5);
t14 = cos(beta);
t15 = sin(t4);
t16 = sin(t11);
t17 = cos(t11);
rRightArm = [rOx+t2.*t8.*1.64721e-3+t2.*t10.*3.18887e-2+t2.*t13.*4.667799999999986e-4+t3.*t12.*3.595415e-2+t3.*t14.*6.272722e-2+t3.*cos(beta-pi.*(1.0./1.8e1)).*1.950677e-2+t3.*t8.*t9.*3.18887e-2-t3.*t9.*t10.*1.64721e-3-t3.*t6.*t15.*2.621678e-2+t3.*t6.*t16.*2.575e-2;rOy-t3.*t8.*1.64721e-3-t3.*t10.*3.18887e-2+t2.*t12.*3.595415e-2+t2.*t14.*6.272722e-2-t3.*t13.*4.667799999999986e-4+t2.*t17.*1.950677e-2+t2.*t8.*t9.*3.18887e-2-t2.*t9.*t10.*1.64721e-3-t2.*t6.*t15.*2.621678e-2+t2.*t6.*t16.*2.575e-2;rOz-t9.*6.272722e-2-t15.*3.595415e-2-t16.*1.950677e-2-t6.*t12.*2.621678e-2+t8.*t14.*3.18887e-2+t6.*t17.*2.575e-2-t10.*t14.*1.64721e-3];
