function vBody = vBody_fn(rOxdot,rOydot,rOzdot)
%VBODY_FN
%    VBODY = VBODY_FN(ROXDOT,ROYDOT,ROZDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:10

vBody = [rOxdot;rOydot;rOzdot];
