function vLeftShoulder = vLeftShoulder_fn(alpha,alphadot,betadot,beta,gammadot,gamma,rOxdot,rOydot,rOzdot)
%VLEFTSHOULDER_FN
%    VLEFTSHOULDER = VLEFTSHOULDER_FN(ALPHA,ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,ROXDOT,ROYDOT,ROZDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:10

t2 = sin(alpha);
t3 = cos(alpha);
t4 = cos(gamma);
t5 = sin(beta);
t6 = sin(gamma);
t7 = pi.*(1.0./1.8e1);
t8 = beta+t7;
t9 = cos(beta);
t10 = cos(t8);
t11 = sin(t8);
vLeftShoulder = [rOxdot+alphadot.*(t3.*t4.*1.64721e-3+t3.*t6.*3.18887e-2+t2.*t9.*6.272722e-2+t2.*t10.*4.23081e-3-t2.*t4.*t5.*3.18887e-2+t2.*t5.*t6.*1.64721e-3)+betadot.*(t3.*t5.*6.272722e-2+t3.*t11.*4.23081e-3+t3.*t4.*t9.*3.18887e-2-t3.*t6.*t9.*1.64721e-3)-gammadot.*(t2.*t4.*(-3.18887e-2)+t2.*t6.*1.64721e-3+t3.*t4.*t5.*1.64721e-3+t3.*t5.*t6.*3.18887e-2);rOydot+alphadot.*(t2.*t4.*1.64721e-3+t2.*t6.*3.18887e-2-t3.*t9.*6.272722e-2-t3.*t10.*4.23081e-3+t3.*t4.*t5.*3.18887e-2-t3.*t5.*t6.*1.64721e-3)+betadot.*(t2.*t5.*6.272722e-2+t2.*t11.*4.23081e-3+t2.*t4.*t9.*3.18887e-2-t2.*t6.*t9.*1.64721e-3)-gammadot.*(t3.*t4.*3.18887e-2-t3.*t6.*1.64721e-3+t2.*t4.*t5.*1.64721e-3+t2.*t5.*t6.*3.18887e-2);rOzdot-gammadot.*(t4.*t9.*1.64721e-3+t6.*t9.*3.18887e-2)+betadot.*(t9.*6.272722e-2+t10.*4.23081e-3-t4.*t5.*3.18887e-2+t5.*t6.*1.64721e-3)];
