function vLeftArm = vLeftArm_fn(alpha,alphadot,betadot,beta,gammadot,gamma,q1,q2,q1dot,q2dot,rOxdot,rOydot,rOzdot)
%VLEFTARM_FN
%    VLEFTARM = VLEFTARM_FN(ALPHA,ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q1,Q2,Q1DOT,Q2DOT,ROXDOT,ROYDOT,ROZDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:11

t2 = pi.*(1.0./1.8e1);
t3 = sin(alpha);
t4 = cos(alpha);
t5 = gamma-q1;
t6 = beta+t2;
t7 = sin(t5);
t8 = beta+q2+t2;
t9 = cos(gamma);
t10 = sin(beta);
t11 = sin(gamma);
t12 = sin(t8);
t13 = cos(t8);
t14 = sin(t6);
t15 = cos(t5);
t16 = t4.*t12.*3.595415e-2;
t17 = cos(t6);
t18 = cos(beta);
t19 = t3.*t7.*4.667799999999986e-4;
t20 = t4.*t12.*t15.*2.621678e-2;
t21 = t3.*t12.*3.595415e-2;
t22 = t3.*t12.*t15.*2.621678e-2;
t23 = t13.*t15.*2.621678e-2;
t24 = t13.*3.595415e-2;
t25 = t7.*t12.*2.621678e-2;
vLeftArm = [rOxdot+betadot.*(t16+t4.*t10.*6.272722e-2+t4.*t14.*1.950677e-2-t4.*t7.*t13.*2.621678e-2+t4.*t7.*t17.*2.575e-2+t4.*t9.*t18.*3.18887e-2-t4.*t11.*t18.*1.64721e-3)-gammadot.*(t19+t20-t3.*t9.*3.18887e-2+t3.*t11.*1.64721e-3+t4.*t9.*t10.*1.64721e-3+t4.*t10.*t11.*3.18887e-2-t4.*t14.*t15.*2.575e-2)+q2dot.*(t16-t4.*t7.*t13.*2.621678e-2)+q1dot.*(t19+t20-t4.*t14.*t15.*2.575e-2)+alphadot.*(t4.*t9.*1.64721e-3+t4.*t11.*3.18887e-2+t3.*t13.*3.595415e-2+t4.*t15.*4.667799999999986e-4+t3.*t17.*1.950677e-2+t3.*t18.*6.272722e-2+t3.*t7.*t12.*2.621678e-2-t3.*t9.*t10.*3.18887e-2-t3.*t7.*t14.*2.575e-2+t3.*t10.*t11.*1.64721e-3);rOydot+betadot.*(t21+t3.*t10.*6.272722e-2+t3.*t14.*1.950677e-2-t3.*t7.*t13.*2.621678e-2+t3.*t7.*t17.*2.575e-2+t3.*t9.*t18.*3.18887e-2-t3.*t11.*t18.*1.64721e-3)-q1dot.*(-t22+t4.*t7.*4.667799999999986e-4+t3.*t14.*t15.*2.575e-2)+q2dot.*(t21-t3.*t7.*t13.*2.621678e-2)-gammadot.*(t22-t4.*t7.*4.667799999999986e-4+t4.*t9.*3.18887e-2-t4.*t11.*1.64721e-3+t3.*t9.*t10.*1.64721e-3+t3.*t10.*t11.*3.18887e-2-t3.*t14.*t15.*2.575e-2)+alphadot.*(t3.*t9.*1.64721e-3+t3.*t11.*3.18887e-2-t4.*t13.*3.595415e-2+t3.*t15.*4.667799999999986e-4-t4.*t17.*1.950677e-2-t4.*t18.*6.272722e-2-t4.*t7.*t12.*2.621678e-2+t4.*t9.*t10.*3.18887e-2+t4.*t7.*t14.*2.575e-2-t4.*t10.*t11.*1.64721e-3);rOzdot+q2dot.*(t24+t25)+betadot.*(t17.*1.950677e-2+t18.*6.272722e-2+t24+t25-t9.*t10.*3.18887e-2-t7.*t14.*2.575e-2+t10.*t11.*1.64721e-3)-gammadot.*(t23+t9.*t18.*1.64721e-3+t11.*t18.*3.18887e-2-t15.*t17.*2.575e-2)+q1dot.*(t23-t15.*t17.*2.575e-2)];
