function vLeftHand = vLeftHand_fn(alpha,alphadot,betadot,beta,gammadot,gamma,q1,q2,q3,q1dot,q2dot,q3dot,rOxdot,rOydot,rOzdot)
%VLEFTHAND_FN
%    VLEFTHAND = VLEFTHAND_FN(ALPHA,ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q1,Q2,Q3,Q1DOT,Q2DOT,Q3DOT,ROXDOT,ROYDOT,ROZDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:11

t2 = pi.*(1.0./1.8e1);
t3 = cos(alpha);
t4 = beta+t2;
t5 = cos(beta);
t6 = gamma-q1;
t7 = sin(t6);
t8 = beta+q2+q3+t2;
t9 = sin(t8);
t10 = t3.*t9.*4.614073e-2;
t11 = cos(t8);
t12 = sin(t4);
t13 = cos(t6);
t14 = sin(alpha);
t15 = sin(gamma);
t16 = t7.*t14.*3.939380000000001e-3;
t17 = cos(gamma);
t18 = sin(beta);
t19 = t3.*t9.*t13.*2.968938e-2;
t20 = cos(t4);
t21 = beta+q2+t2;
t22 = sin(t21);
t23 = t3.*t22.*(9.0./1.25e2);
t24 = cos(t21);
t25 = t3.*t7.*3.939380000000001e-3;
t26 = t12.*t13.*t14.*2.575e-2;
t27 = t9.*t14.*4.614073e-2;
t28 = t14.*t22.*(9.0./1.25e2);
t29 = t11.*4.614073e-2;
t30 = t7.*t9.*2.968938e-2;
t31 = t11.*t13.*2.968938e-2;
t32 = t24.*(9.0./1.25e2);
vLeftHand = [rOxdot+alphadot.*(t3.*t13.*3.939380000000001e-3+t3.*t15.*3.18887e-2+t5.*t14.*6.272722e-2+t3.*t17.*1.64721e-3+t11.*t14.*4.614073e-2+t14.*t20.*1.950677e-2+t14.*t24.*(9.0./1.25e2)+t7.*t9.*t14.*2.968938e-2-t7.*t12.*t14.*2.575e-2+t14.*t15.*t18.*1.64721e-3-t14.*t17.*t18.*3.18887e-2)-gammadot.*(t16+t19+t14.*t15.*1.64721e-3-t14.*t17.*3.18887e-2-t3.*t12.*t13.*2.575e-2+t3.*t15.*t18.*3.18887e-2+t3.*t17.*t18.*1.64721e-3)+q3dot.*(t10-t3.*t7.*t11.*2.968938e-2)+betadot.*(t10+t23+t3.*t12.*1.950677e-2+t3.*t18.*6.272722e-2-t3.*t7.*t11.*2.968938e-2-t3.*t5.*t15.*1.64721e-3+t3.*t5.*t17.*3.18887e-2+t3.*t7.*t20.*2.575e-2)+q1dot.*(t16+t19-t3.*t12.*t13.*2.575e-2)+q2dot.*(t10+t23-t3.*t7.*t11.*2.968938e-2);rOydot-alphadot.*(t3.*t5.*6.272722e-2+t3.*t11.*4.614073e-2+t3.*t20.*1.950677e-2+t3.*t24.*(9.0./1.25e2)-t13.*t14.*3.939380000000001e-3-t14.*t15.*3.18887e-2-t14.*t17.*1.64721e-3+t3.*t7.*t9.*2.968938e-2-t3.*t7.*t12.*2.575e-2+t3.*t15.*t18.*1.64721e-3-t3.*t17.*t18.*3.18887e-2)-gammadot.*(-t25-t26-t3.*t15.*1.64721e-3+t3.*t17.*3.18887e-2+t9.*t13.*t14.*2.968938e-2+t14.*t15.*t18.*3.18887e-2+t14.*t17.*t18.*1.64721e-3)+q3dot.*(t27-t7.*t11.*t14.*2.968938e-2)+betadot.*(t27+t28+t12.*t14.*1.950677e-2+t14.*t18.*6.272722e-2-t7.*t11.*t14.*2.968938e-2-t5.*t14.*t15.*1.64721e-3+t5.*t14.*t17.*3.18887e-2+t7.*t14.*t20.*2.575e-2)-q1dot.*(t25+t26-t9.*t13.*t14.*2.968938e-2)+q2dot.*(t27+t28-t7.*t11.*t14.*2.968938e-2);rOzdot+q3dot.*(t29+t30)+q2dot.*(t29+t30+t32)-gammadot.*(t31+t5.*t15.*3.18887e-2+t5.*t17.*1.64721e-3-t13.*t20.*2.575e-2)+q1dot.*(t31-t13.*t20.*2.575e-2)+betadot.*(t5.*6.272722e-2+t20.*1.950677e-2+t29+t30+t32-t7.*t12.*2.575e-2+t15.*t18.*1.64721e-3-t17.*t18.*3.18887e-2)];
