function vRightHip = vRightHip_fn(alpha,alphadot,betadot,beta,gammadot,gamma,q4,q4dot,rOxdot,rOydot,rOzdot)
%VRIGHTHIP_FN
%    VRIGHTHIP = VRIGHTHIP_FN(ALPHA,ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q4,Q4DOT,ROXDOT,ROYDOT,ROZDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:17

t2 = sin(alpha);
t3 = sin(gamma);
t4 = cos(alpha);
t5 = cos(gamma);
t6 = sin(beta);
t7 = beta-q4;
t8 = sin(t7);
t9 = cos(t7);
t10 = t4.*t8.*1.065566e-2;
t11 = cos(beta);
t12 = t4.*t5.*t9.*2.68635e-3;
t13 = t3.*t4.*t9.*1.458538e-2;
t14 = t2.*t8.*1.065566e-2;
t15 = t2.*t3.*t9.*1.458538e-2;
t16 = t2.*t5.*t9.*2.68635e-3;
t17 = t9.*1.065566e-2;
vRightHip = [rOxdot-alphadot.*(t3.*t4.*9.535293999999999e-2+t4.*t5.*8.71741e-3+t2.*t9.*1.065566e-2+t2.*t11.*3.172834e-2+t2.*t3.*t6.*2.330279e-2-t2.*t3.*t8.*1.458538e-2-t2.*t5.*t6.*9.266658999999999e-2-t2.*t5.*t8.*2.68635e-3)-betadot.*(t10+t12+t13+t4.*t6.*3.172834e-2-t3.*t4.*t11.*2.330279e-2+t4.*t5.*t11.*9.266658999999999e-2)+q4dot.*(t10+t12+t13)+gammadot.*(t2.*t3.*8.71741e-3-t2.*t5.*9.535293999999999e-2+t3.*t4.*t6.*9.266658999999999e-2+t3.*t4.*t8.*2.68635e-3+t4.*t5.*t6.*2.330279e-2-t4.*t5.*t8.*1.458538e-2);rOydot-alphadot.*(t2.*t3.*9.535293999999999e-2+t2.*t5.*8.71741e-3-t4.*t9.*1.065566e-2-t4.*t11.*3.172834e-2-t3.*t4.*t6.*2.330279e-2+t3.*t4.*t8.*1.458538e-2+t4.*t5.*t6.*9.266658999999999e-2+t4.*t5.*t8.*2.68635e-3)-betadot.*(t14+t15+t16+t2.*t6.*3.172834e-2-t2.*t3.*t11.*2.330279e-2+t2.*t5.*t11.*9.266658999999999e-2)+q4dot.*(t14+t15+t16)+gammadot.*(t3.*t4.*(-8.71741e-3)+t4.*t5.*9.535293999999999e-2+t2.*t3.*t6.*9.266658999999999e-2+t2.*t3.*t8.*2.68635e-3+t2.*t5.*t6.*2.330279e-2-t2.*t5.*t8.*1.458538e-2);rOzdot-q4dot.*(-t17+t3.*t8.*1.458538e-2+t5.*t8.*2.68635e-3)-betadot.*(t11.*3.172834e-2+t17+t3.*t6.*2.330279e-2-t3.*t8.*1.458538e-2-t5.*t6.*9.266658999999999e-2-t5.*t8.*2.68635e-3)+gammadot.*(t3.*t9.*2.68635e-3+t3.*t11.*9.266658999999999e-2-t5.*t9.*1.458538e-2+t5.*t11.*2.330279e-2)];
