function vRightArm = vRightArm_fn(alpha,alphadot,betadot,beta,gammadot,gamma,q9,q10,q10dot,q9dot,rOxdot,rOydot,rOzdot)
%VRIGHTARM_FN
%    VRIGHTARM = VRIGHTARM_FN(ALPHA,ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q9,Q10,Q10DOT,Q9DOT,ROXDOT,ROYDOT,ROZDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:12

t4 = pi.*(1.0./1.8e1);
t2 = beta+q10-t4;
t3 = cos(alpha);
t5 = cos(t2);
t6 = sin(alpha);
t7 = gamma+q9;
t8 = sin(t2);
t9 = sin(t7);
t10 = beta-t4;
t11 = cos(gamma);
t12 = sin(beta);
t13 = sin(gamma);
t14 = sin(t10);
t15 = t3.*t8.*3.595415e-2;
t16 = t3.*t5.*t9.*2.621678e-2;
t17 = cos(t10);
t18 = cos(beta);
t19 = cos(t7);
t20 = t6.*t9.*4.667799999999986e-4;
t21 = t3.*t8.*t19.*2.621678e-2;
t22 = t6.*t8.*3.595415e-2;
t23 = t5.*t6.*t9.*2.621678e-2;
t24 = t3.*t9.*4.667799999999986e-4;
t25 = t6.*t14.*t19.*2.575e-2;
t26 = t5.*t19.*2.621678e-2;
t27 = t5.*3.595415e-2;
vRightArm = [rOxdot-q10dot.*(t15+t16)-gammadot.*(t20+t21-t6.*t11.*3.18887e-2+t6.*t13.*1.64721e-3+t3.*t11.*t12.*1.64721e-3+t3.*t12.*t13.*3.18887e-2-t3.*t14.*t19.*2.575e-2)-betadot.*(t15+t16+t3.*t12.*6.272722e-2+t3.*t14.*1.950677e-2-t3.*t9.*t17.*2.575e-2-t3.*t11.*t18.*3.18887e-2+t3.*t13.*t18.*1.64721e-3)-q9dot.*(t20+t21-t3.*t14.*t19.*2.575e-2)-alphadot.*(t5.*t6.*3.595415e-2-t3.*t11.*1.64721e-3-t3.*t13.*3.18887e-2-t3.*t19.*4.667799999999986e-4+t6.*t17.*1.950677e-2+t6.*t18.*6.272722e-2-t6.*t8.*t9.*2.621678e-2+t6.*t9.*t14.*2.575e-2+t6.*t11.*t12.*3.18887e-2-t6.*t12.*t13.*1.64721e-3);rOydot-q10dot.*(t22+t23)+q9dot.*(t24+t25-t6.*t8.*t19.*2.621678e-2)-gammadot.*(-t24-t25+t3.*t11.*3.18887e-2-t3.*t13.*1.64721e-3+t6.*t11.*t12.*1.64721e-3+t6.*t12.*t13.*3.18887e-2+t6.*t8.*t19.*2.621678e-2)-betadot.*(t22+t23+t6.*t12.*6.272722e-2+t6.*t14.*1.950677e-2-t6.*t9.*t17.*2.575e-2-t6.*t11.*t18.*3.18887e-2+t6.*t13.*t18.*1.64721e-3)+alphadot.*(t3.*t5.*3.595415e-2+t6.*t11.*1.64721e-3+t6.*t13.*3.18887e-2+t3.*t17.*1.950677e-2+t3.*t18.*6.272722e-2+t6.*t19.*4.667799999999986e-4-t3.*t8.*t9.*2.621678e-2+t3.*t9.*t14.*2.575e-2+t3.*t11.*t12.*3.18887e-2-t3.*t12.*t13.*1.64721e-3);rOzdot-q10dot.*(t27-t8.*t9.*2.621678e-2)-betadot.*(t17.*1.950677e-2+t18.*6.272722e-2+t27-t8.*t9.*2.621678e-2+t9.*t14.*2.575e-2+t11.*t12.*3.18887e-2-t12.*t13.*1.64721e-3)-gammadot.*(t26+t11.*t18.*1.64721e-3+t13.*t18.*3.18887e-2-t17.*t19.*2.575e-2)-q9dot.*(t26-t17.*t19.*2.575e-2)];
