function vRightHand = vRightHand_fn(alpha,alphadot,betadot,beta,gammadot,gamma,q9,q10,q11,q10dot,q11dot,q9dot,rOxdot,rOydot,rOzdot)
%VRIGHTHAND_FN
%    VRIGHTHAND = VRIGHTHAND_FN(ALPHA,ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q9,Q10,Q11,Q10DOT,Q11DOT,Q9DOT,ROXDOT,ROYDOT,ROZDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:13

t2 = cos(alpha);
t4 = pi.*(1.0./1.8e1);
t3 = beta+q10+q11-t4;
t5 = beta+q10-t4;
t6 = sin(t5);
t7 = t2.*t6.*(9.0./1.25e2);
t8 = sin(t3);
t9 = t2.*t8.*4.614073e-2;
t10 = gamma+q9;
t11 = sin(t10);
t12 = cos(t3);
t13 = t2.*t11.*t12.*2.968937e-2;
t14 = beta-t4;
t15 = cos(beta);
t16 = cos(t10);
t17 = sin(t14);
t18 = sin(alpha);
t19 = sin(gamma);
t20 = t11.*t18.*3.93937e-3;
t21 = cos(gamma);
t22 = t2.*t8.*t16.*2.968937e-2;
t23 = sin(beta);
t24 = cos(t14);
t25 = t6.*t18.*(9.0./1.25e2);
t26 = t8.*t18.*4.614073e-2;
t27 = t11.*t12.*t18.*2.968937e-2;
t28 = cos(t5);
t29 = t2.*t11.*3.93937e-3;
t30 = t16.*t17.*t18.*2.575e-2;
t31 = t12.*4.614073e-2;
t32 = t12.*t16.*2.968937e-2;
t33 = t28.*(9.0./1.25e2);
vRightHand = [rOxdot-q11dot.*(t9+t13)-betadot.*(t7+t9+t13+t2.*t17.*1.950677e-2+t2.*t23.*6.272722e-2+t2.*t15.*t19.*1.64721e-3-t2.*t11.*t24.*2.575e-2-t2.*t15.*t21.*3.18887e-2)-gammadot.*(t20+t22+t18.*t19.*1.64721e-3-t18.*t21.*3.18887e-2-t2.*t16.*t17.*2.575e-2+t2.*t19.*t23.*3.18887e-2+t2.*t21.*t23.*1.64721e-3)-q10dot.*(t7+t9+t13)-alphadot.*(t2.*t16.*(-3.93937e-3)-t2.*t19.*3.18887e-2-t2.*t21.*1.64721e-3+t12.*t18.*4.614073e-2+t15.*t18.*6.272722e-2+t18.*t24.*1.950677e-2+t18.*t28.*(9.0./1.25e2)-t8.*t11.*t18.*2.968937e-2+t11.*t17.*t18.*2.575e-2-t18.*t19.*t23.*1.64721e-3+t18.*t21.*t23.*3.18887e-2)-q9dot.*(t20+t22-t2.*t16.*t17.*2.575e-2);rOydot-q11dot.*(t26+t27)-gammadot.*(-t29-t30-t2.*t19.*1.64721e-3+t2.*t21.*3.18887e-2+t8.*t16.*t18.*2.968937e-2+t18.*t19.*t23.*3.18887e-2+t18.*t21.*t23.*1.64721e-3)-betadot.*(t25+t26+t27+t17.*t18.*1.950677e-2+t18.*t23.*6.272722e-2+t15.*t18.*t19.*1.64721e-3-t11.*t18.*t24.*2.575e-2-t15.*t18.*t21.*3.18887e-2)-q10dot.*(t25+t26+t27)+alphadot.*(t2.*t12.*4.614073e-2+t2.*t15.*6.272722e-2+t2.*t24.*1.950677e-2+t2.*t28.*(9.0./1.25e2)+t16.*t18.*3.93937e-3+t18.*t19.*3.18887e-2+t18.*t21.*1.64721e-3-t2.*t8.*t11.*2.968937e-2+t2.*t11.*t17.*2.575e-2-t2.*t19.*t23.*1.64721e-3+t2.*t21.*t23.*3.18887e-2)+q9dot.*(t29+t30-t8.*t16.*t18.*2.968937e-2);rOzdot-q10dot.*(t31+t33-t8.*t11.*2.968937e-2)-betadot.*(t15.*6.272722e-2+t24.*1.950677e-2+t31+t33-t8.*t11.*2.968937e-2+t11.*t17.*2.575e-2-t19.*t23.*1.64721e-3+t21.*t23.*3.18887e-2)-gammadot.*(t32+t15.*t19.*3.18887e-2+t15.*t21.*1.64721e-3-t16.*t24.*2.575e-2)-q11dot.*(t31-t8.*t11.*2.968937e-2)-q9dot.*(t32-t16.*t24.*2.575e-2)];
