function vRightThigh = vRightThigh_fn(alpha,alphadot,betadot,beta,gammadot,gamma,q4,q5,q4dot,q5dot,rOxdot,rOydot,rOzdot)
%VRIGHTTHIGH_FN
%    VRIGHTTHIGH = VRIGHTTHIGH_FN(ALPHA,ALPHADOT,BETADOT,BETA,GAMMADOT,GAMMA,Q4,Q5,Q4DOT,Q5DOT,ROXDOT,ROYDOT,ROZDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    18-Oct-2018 14:10:18

t2 = cos(alpha);
t3 = sin(alpha);
t4 = beta-q4;
t5 = cos(gamma);
t6 = sin(t4);
t7 = sin(gamma);
t8 = gamma+q5;
t9 = sin(beta);
t10 = cos(t8);
t11 = sin(t8);
t12 = t3.*t10.*1.304877e-2;
t13 = cos(t4);
t14 = t2.*t6.*9.760599999999999e-3;
t15 = cos(beta);
t16 = t2.*t10.*t13.*1.304877e-2;
t17 = t2.*t5.*t13.*(7.0./2.0e2);
t18 = t2.*t7.*t13.*3.225e-2;
t19 = t2.*t10.*1.304877e-2;
t20 = t3.*t6.*t11.*1.304877e-2;
t21 = t3.*t6.*9.760599999999999e-3;
t22 = t3.*t7.*t13.*3.225e-2;
t23 = t3.*t10.*t13.*1.304877e-2;
t24 = t3.*t5.*t13.*(7.0./2.0e2);
t25 = t6.*t10.*1.304877e-2;
t26 = t5.*t6.*(7.0./2.0e2);
t27 = t6.*t7.*3.225e-2;
vRightThigh = [rOxdot-gammadot.*(t12+t3.*t5.*1.2766659e-1+t3.*t7.*8.94721e-3+t2.*t5.*t6.*3.225e-2-t2.*t6.*t7.*(7.0./2.0e2)-t2.*t5.*t9.*2.330279e-2-t2.*t7.*t9.*9.266658999999999e-2-t2.*t6.*t11.*1.304877e-2)+alphadot.*(t2.*t5.*8.94721e-3-t2.*t7.*1.2766659e-1-t2.*t11.*1.304877e-2-t3.*t13.*9.760599999999999e-3-t3.*t15.*3.172834e-2+t3.*t5.*t6.*(7.0./2.0e2)+t3.*t6.*t7.*3.225e-2+t3.*t5.*t9.*9.266658999999999e-2+t3.*t6.*t10.*1.304877e-2-t3.*t7.*t9.*2.330279e-2)-q5dot.*(t12-t2.*t6.*t11.*1.304877e-2)-betadot.*(t14+t16+t17+t18+t2.*t9.*3.172834e-2+t2.*t5.*t15.*9.266658999999999e-2-t2.*t7.*t15.*2.330279e-2)+q4dot.*(t14+t16+t17+t18);rOydot+q5dot.*(t19+t20)-alphadot.*(t3.*t5.*(-8.94721e-3)+t3.*t7.*1.2766659e-1+t3.*t11.*1.304877e-2-t2.*t13.*9.760599999999999e-3-t2.*t15.*3.172834e-2+t2.*t5.*t6.*(7.0./2.0e2)+t2.*t6.*t7.*3.225e-2+t2.*t5.*t9.*9.266658999999999e-2+t2.*t6.*t10.*1.304877e-2-t2.*t7.*t9.*2.330279e-2)+gammadot.*(t19+t20+t2.*t5.*1.2766659e-1+t2.*t7.*8.94721e-3-t3.*t5.*t6.*3.225e-2+t3.*t6.*t7.*(7.0./2.0e2)+t3.*t5.*t9.*2.330279e-2+t3.*t7.*t9.*9.266658999999999e-2)-betadot.*(t21+t22+t23+t24+t3.*t9.*3.172834e-2+t3.*t5.*t15.*9.266658999999999e-2-t3.*t7.*t15.*2.330279e-2)+q4dot.*(t21+t22+t23+t24);rOzdot+betadot.*(t13.*(-9.760599999999999e-3)-t15.*3.172834e-2+t25+t26+t27+t5.*t9.*9.266658999999999e-2-t7.*t9.*2.330279e-2)+gammadot.*(t5.*t13.*(-3.225e-2)+t5.*t15.*2.330279e-2+t7.*t13.*(7.0./2.0e2)+t7.*t15.*9.266658999999999e-2+t11.*t13.*1.304877e-2)-q4dot.*(t13.*(-9.760599999999999e-3)+t25+t26+t27)+q5dot.*t11.*t13.*1.304877e-2];
